### ISSUE TITLE
Улучшение сервиса

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForAndroid#10]
Здравствуйте,
Я предлагаю убрать регу вначале.
Для бесплатных аккаунтов без регистрации вовсе, а для платных добавить возможность активации лицензионным ключём

**Comment by AlfredSpijker** [comment]
Please post in English only. Thank you.

**Comment by zzebrum** [comment]
Бесплатный трафик дается на зарегистрированный аккаунт.
