### ISSUE TITLE
Does AdGuardVPN not support LAN proxy? 

### ISSUE THREAD

**Issue by pongfcnkl** [AdguardTeam/AdGuardVPNForAndroid#103]
### Prerequisites

- [yes ] I am running the latest version
- [yes  ] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Problem Description

I use Ubuntu. Since AdGuardVPN does not support Linux systems, we can only consider using AdGuardVPN to open socks5  and set the phone's ip and port on ubuntu, but it seems that it cannot be connected 
### Proposed Solution
Add LAN proxy function 

### Alternatives Considered
no

**Comment by anastenko** [comment]
@pongfcnkl Hello.
Sorry for the late reply.
We have a license system, which blocks users from using hotspot, cause in that case users could connect lots of devices to 1 single license. That's why it's irrational to add LAN proxy function.
