### ISSUE TITLE
Netflix video playback issues while AG VPN and AG Adblocker work in compatibility mode

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardVPNForAndroid#105]
### Issue Details

Netflix works when watched with just the vpn, or no vpn, but when using adguard and adguard vpn together in compatibility mode it stops. 

 **Device:**
pixel 5 phones (one on Android 11 one on Android 12)
Amazon hd 8 tablet Android 10

Ticket number [#515057](https://adguard.zendesk.com/agent/tickets/515057)

**Comment by anastenko** [comment]
User needs to turn the DNS filtering off and try using a different server. Let us know once tried.

**Comment by Effsi** [comment]
same issue with advised settings, 5 different servers tried.

**Comment by anastenko** [comment]
@Effsi Hello.
So it works when the VPN is on and off, and doesn't work with the AG + VPN compatibility mode.

What happens if only AG is enabled?

**Comment by Effsi** [comment]
the only time it does not work is using the two together

**Comment by artemiv4nov** [comment]
@anastenko Can we reproduce it? We need to collect the debug logs from both applications.

**Comment by Birbber** [comment]
@artemiv4nov Please see the logs attached.

**Comment by artemiv4nov** [comment]
Well, no reaction for long time. I'll close this task, re-open if needed
