### ISSUE TITLE
[Bug] Cannot connected to Japan VPN server

### ISSUE THREAD

**Issue by SaberAkiyama** [AdguardTeam/AdGuardVPNForAndroid#107]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  v1.2.1 (115)
- **VPN mode:**
  -  Compatibility mode with AdGuard
- **Device:**
  -  Leagoo Leapad 7
- **Operating system and version:**
  -  Android 6.0
- **Root access:**
  -  No

### Expected Behavior

I try to connect to Japan VPN server, but it didn't connect it. Others are normal with no issue. 

### Actual Behavior
Causing didn't respond to Japan VPN server

### Screenshots

<details><summary>Screenshot:</summary>

![20210717_135237](https://user-images.githubusercontent.com/48464326/126027751-c751db12-857e-43b1-b4f8-b2ecff38475d.jpg)

</details>

### Additional Information

None

**Comment by SaberAkiyama** [comment]
Still waiting for fix VPN server

**Comment by anastenko** [comment]
@SaberAkiyama Hello.
Couldn't reproduce it on our end. The server works just fine.
Did you try connecting to another one and re-connecting to Japan?

**Comment by SaberAkiyama** [comment]
> @SaberAkiyama Hello.
> Couldn't reproduce it on our end. The server works just fine.
> Did you try connecting to another one and re-connecting to Japan?

I use for USA server, and then re-connecting to Japan server, but it not responding to the server. Others are normal.

**Comment by anastenko** [comment]
Could you please send us the debug logs? 

Here's how to do it:
- Open App settings --> Advanced settings --> Logging level --> Extended;
- Reproduce the issue (and remember the exact time when it happened);
- Export logs and system info. Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by SaberAkiyama** [comment]
I don't think my tablet is not compatible with VPN server. Well, I guess I use Android VPN built-in. Thanks. And I'm closed the issues.
