### ISSUE TITLE
Unable to use Airtel Extreme Application of INDIA /  Airtel TV 

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardVPNForAndroid#11]
### Issue Details

- **AdGuard VPN version:**
  -  1.0.136 / 1.0.147
- **VPN mode:**
  -  SOCKS5/VPN

### Actual Behavior

Unable to use the Airtel Extreme Application of INDIA.

While using Indian Server in the VPN, in order to stream local Indian
content by using airtel application. The application first opens as it
recognizes Indian IP but while placing any video or doing live streaming,
the content does not play and an error occurred. Tried many times even
using 4g, 5g, and good wifi connection.

**Comment by TheHasagi** [comment]
Unfortunately, it is unable to use VPN with such stream service.
