### ISSUE TITLE
AdGuard VPN blocks Yandex browser

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardVPNForAndroid#120]
### Issue Details
При включенном Adguard VPN перестают работать видео в яндекс браузере, когда листаешь главную страницу. (Крутится белый кружок, видео не загружается). Также приложение "Пятерочка"  и некоторые другие приложения не работают. 

- **AdGuard VPN version:**
1.2.115 
- **Device:**
  Xiaomi Mi 9T Pro
- **Operating system and version:**
  Android 11

**Comment by admitrevskiy** [comment]
Пользователь не отвечает, переоткроем задачу, если вернется с подробностями.
