### ISSUE TITLE
Main screen doesn't change its state to "Network is lost" after turning the network off

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardVPNForAndroid#129]
AdGuard version: v2.0 beta 1 (89)

### Issue Details

When you disable the network the main screen changes from "Connected" to "Waiting for connection". After 5 seconds it should change to "Network is lost" screen, but it doesn't.

**Comment by SaberAkiyama** [comment]
Same. I was connect to USA VPN server, it said "Connected", few seconds later, it's suddenly "Waiting for connection".

By the way, I use compatibility mode with Adguard adblocker

**Comment by Birbber** [comment]
@SaberAkiyama Most likely you're talking about a different issue. This one is about lost network, for example, when you turn Wifi off and it tries to re-connect.
