### ISSUE TITLE
Adguard + Adguard VPN Compatibility Mode Explanation

### ISSUE THREAD

**Issue by DrSuSE** [AdguardTeam/AdGuardVPNForAndroid#141]
This isn't really a bug report, but I was sent here by support.

Is there an explanation of how compatibility mode works?  The UI (notifications) imply that it just makes the VPN proxy mode meaning there is not necessarily any encryption happening... but I assume this is not the case since that would make compatibility mode just the same as proxy mode really.

I have also noticed a severe drop off in speed in the last month (on all US servers), but that's a whole other issue.

Android 11 and 12, not that the specific version matters for this explanation.

**Comment by ameshkov** [comment]
Well, here's what's going on:

1. The VPN app opens an encrypted tunnel to the remote VPN server.
2. At the same time it creates a local proxy server.
3. The ad blocker app reroutes traffic to that local proxy.

So in the end, the traffic goes like this:
Your apps --> AdGuard app ---> AdGuard VPN app ---> encrypted tunnel ---> remote VPN server
