### ISSUE TITLE
VPN gets disconnected when the connection is not stable

### ISSUE THREAD

**Issue by Birbber** [AdguardTeam/AdGuardVPNForAndroid#143]
The VPN seems to disconnect randomly, but it's assumed to happen when signal gets low. Both wifi and mobile networks are affected. 

What we need to do is make the app reconnect when the connection gets dodgy, and if one server is failing, it needs to auto-connect to another one. Currently it just says "Not connected".

- **AdGuard VPN version:**
 - v2.0 pre-alpha 11(119)
 
 Ticket: 526423

**Comment by infinitewaveparticle** [comment]
I have seen many people in the reviews on Google Play and also in the forum complaining about this issue. I also suffer from it. Like I've said in other issues (read my comments from the issues below this one too), for some reason switching the logging level for AdGuard VPN to 'Extended' prevents AdGuard VPN from disconnecting. While I second forcing AdGuard VPN to reconnect and to choose a faster server if that fails, perhaps you can use this "fix" I've noticed to help prevent it from disconnecting in the first place. Also, for Compatibility Mode, when AdGuard VPN disconnects the automatically-created SOCKS5 connection needs to remain enabled and the AdGuard app needs to not restart its connection. If the user wants to disable AdGuard VPN and use only the AdGuard app, then perhaps you should add a second button for while in Compatibility Mode called 'Unlink' (and the description for the Unlink button can be something like "disable AdGuard VPN and use AdGuard AdBlocker only"). In the case of Unlink being clicked only then should the SOCKS5 connection be disabled/killed and the AdGuard app restart its connection.

**Comment by artemiv4nov** [comment]
Hi! Please re-check the issue on the latest beta version, we updated VpnLibs

**Comment by AlfredSpijker** [comment]
> Hi! Please re-check the issue on the latest beta version, we updated VpnLibs

Also in the Alpha (via Play Store)?
Running 2.1.2 now. No update available.

**Comment by artemiv4nov** [comment]
@AlfredSpijker Hello! On the previous week we released the new Beta.
Can you re-check please on the latest Beta? The new pre-alpha will be available today, also.

**Comment by AlfredSpijker** [comment]
> @AlfredSpijker Hello! On the previous week we released the new Beta.
> Can you re-check please on the latest Beta? The new pre-alpha will be available today, also.

@artemiv4nov Running 2.1.20 now (via Play Store).
Will report back.

**Comment by artemiv4nov** [comment]
@AlfredSpijker this issue still relevant?

**Comment by AlfredSpijker** [comment]
> @AlfredSpijker this issue still relevant?

Yes, it is.

Tested the last weeks with AG v. 3.6.8 (46) and AG-VPN v. 2.1 pre-alpha 4 (25) running on OnePlus6T with Android 11 (always connected to 4G) and Google Pixel C with Android 8 (always connected to WiFi). On the OnePlus6T all known battery settings are made to avoid killing by Android. 

The goods news is now on both devices a (re)boot always results to start, run and connect AG and AG-VPN in compatability mode as configured. Great.

But on both devices there are several disconnects/reconnects during the day when in use. Mostly the reconnections went flawlessly. But after each reconnection several running apps "complains" they lost network connection and I have to refresh them repeatedly to work ok. 

And there is still an issue with the disconnection and not reconnect when idle (mostly during the nights). On the OnePlus6T AG-VPN always reports in the morning "Connecting..." and the network connection is blocked. Nothing works on AG-VPN anymore. I have to force stop AG-VPN and restart it through AG.

**Comment by artemiv4nov** [comment]
Well, I think the problem with unstable connection has gone on the 2.2 version

**Comment by AlfredSpijker** [comment]
> Well, I think the problem with unstable connection has gone on the 2.2 version

This issue from my last comment still occurs:

_And there is still an issue with the disconnection and not reconnect when idle (mostly during the nights). On the OnePlus6T AG-VPN always reports in the morning "Connecting..." and the network connection is blocked. Nothing works on AG-VPN anymore. I have to force stop AG-VPN and restart it through AG._

**Comment by aliafshany** [comment]
> 
@artemiv4nov 
i'm using `Version 2.9.0.1206 release`
so it's not gone
