### ISSUE TITLE
Display some information about what server you are connected to

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForAndroid#153]
Why does the VPN app not show the current connection??? 

It should display "Real IP: XYZ" and "VPN IP: ABC", and also "Current Location: Australia" and "VPN Server: Brazil". 

Please display some information about what server you are connected to. Currently it only says "connected". Nothing more... 
It does not show the connection time, only in the notification bar. 

It also does not show a timer for the connection. This helps in troubleshooting and determining if connections are unstable, eg. connection lost is screen off, or app instability, or OS instability, etc etc etc. 

Would you please consider these requests and feedback? 
A. Display current GEO IP & VPN IP.
B. Display current GEO location & VPN server.
C. Display more details of the connection (Eg. "connecting...", "please wait...", "connection error", "connection failed", etc etc etc).
D. Timer showing connection time (2 days 5hr 31min, OR connected at 11:35am 25th Dec).

**Comment by artemiv4nov** [comment]
@Eugene-Savenko Hi!
We display additional information about the current connection in the Diagnostic Info dialog.
You can find it in the "Settings -> Advanced settings".
