### ISSUE TITLE
AG pauses protection with latest AG VPN from GPlay

### ISSUE THREAD

**Issue by Globulopolis** [AdguardTeam/AdGuardVPNForAndroid#159]
### Issue Details

- **AdGuard version:**
  - 3.6.7(41)
- **AdGuard VPN version:**
  - 2.0.154
- **VPN mode:**
  - Local VPN
- **Device:**
  - Samsung  Galaxy S9+
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

Working protection in AG.

### Actual Behavior

Protection on pause until we disconnect/turn off AG VPN.

### Steps to reproduce

- Open AG go to settings, tap on AdGuard VPN.
- Tap on 'Connect', wait until connect.

**Comment by infinitewaveparticle** [comment]
I've been hesitant to update AdGuard VPN to version 2.0 - is everyone experiencing this? Has anyone tried it with any 4.0 Nightly versions of AdGuard? Or on Android 5, 7, 8, or Android TV?

**Comment by Birbber** [comment]
@Globulopolis Will close this one as a duplicate of [#160](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/160). Both concern the same issue.
