### ISSUE TITLE
No connection when proxy disabled.

### ISSUE THREAD

**Issue by RonKhondji** [AdguardTeam/AdGuardVPNForAndroid#16]
- **AdGuard VPN version:**
 v1.0.147

- **VPN mode:**
SOCKS5

- **Operating system and version:**
Android 10

- **Root access:**
No

### Actual Behavior
When using Adguard VPN as a proxy for Adguard for Android the device has no internet connection if proxy is disabled.

### Expected Behavior
After disabling the proxy there should be a insecure connection to the internet.

**Comment by zzebrum** [comment]
@RonKhondji try the latest VPN version 1.0.155 and AdGuard nightly version 3.5.40. They both have a lot of improvements from the integration perspective.

**Comment by RonKhondji** [comment]
Yep. That did it.
Looking good.
