### ISSUE TITLE
Fix the AdGuard compatibility common issues

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/AdGuardVPNForAndroid#166]
Well, we have one more situation with the AdGuard compatibility mode. Unfortunately, we have a lot of support requests about the AdGuard and AdGuard VPN applications don't work correctly in the Compatibility mode.

This case exists more than one year, and users could be touched with the issue super rare. However, after the AdGuard VPN 2.0 version has been released, this issue became to be shown many times more.

I initiate a new task to figure out with the issue and try to fix it.

If you have the same issue, please make a "+" reaction to this post.

**Comment by artemiv4nov** [comment]
**Update:**
We applied a few minor fixes for the compatibility mode, they will available in the next version.

**Comment by infinitewaveparticle** [comment]
I'm going to make a brand new issue with detailed specifics. I've already sent logs. I'll let you be the judge as to whether or not to keep the issues separate.

**Comment by Nzzyme** [comment]
@artemiv4nov : I am facing a compatibility issue too. Please check this https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/179
