### ISSUE TITLE
Different results on test page with different browsers though same VPN & AG states

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardVPNForAndroid#17]
### Issue Details

- **AdGuard VPN version:**
  -  1.0.155
- **VPN mode:**
  -  AG Android App integration
- **Device:**
  -  Moto G7
- **Operating system and version:**
  -  Android 10 stock
- **Root access:**
  -  No

### Expected Behavior

On https://adguard.com/en/test.html , consistent results between different browsers showing both AG & AG VPN active operation

### Actual Behavior

With otherwise identical state, different browsers show different results on test page

### Screenshots

<details><summary><a href="https://play.google.com/store/apps/details?id=org.mozilla.focus">Ff Focus</a>:</summary>

![Screenshot_20200820-201552.png](https://user-images.githubusercontent.com/185902/90839842-7b975880-e326-11ea-8760-e63a80007c5e.png)
</details>

<details><summary><a href="https://play.google.com/store/apps/details?id=com.microsoft.emmx">MSEdge</a>:</summary>

![Screenshot_20200820-201925.png](https://user-images.githubusercontent.com/185902/90839853-84882a00-e326-11ea-8cf3-03e40ac4731e.png)
</details>

<details><summary><a href="https://play.google.com/store/apps/details?id=com.lastpass.lpandroid">LastPass Browser</a>:</summary>

![Screenshot_20200820-202041.png](https://user-images.githubusercontent.com/185902/90839866-89e57480-e326-11ea-9733-0d62ef3ccb66.png)
</details>

**Comment by Chinaski1** [comment]
Hello @TPS!
Please, clarify the following information:
- Are the AdGuard and AdGuard VPN configured as shown in the screenshots? (Intgration mode)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/91182022-4efe8a80-e6f2-11ea-9f4d-4fd70eb202e0.png)

</details>
<details><summary>Screenshot:</summary>


![image](https://user-images.githubusercontent.com/49645813/91182049-5756c580-e6f2-11ea-8260-e0e40d6ae040.png)

</details>

- Does the issue reproduce itself only in the specified browsers? 
- Can you provide links to download browsers that you mention earlier?
- What version of AdGuard App are you using?

**Comment by TPS** [comment]
@Chinaski1 Sorry about the delay replying.  In order of your questions:
1. Yes.
2. Those are the only browsers I keep active on my phone, so I can't answer for any others.
3. I've added GPlay links to the browser names in my OP, ↑.
4. Always the latest ηightly, currently v4.0η1(3).

**Comment by Revertron** [comment]
It seams that our test page relies on HTTPS-filtering a lot. If you open it on browsers without HTTPS-filtering on you will get strange results.
And there is no correlation to AdGuard VPN or integration with AdGuard itself.

**Comment by TPS** [comment]
@Revertron That _somewhat_ makes sense, since, of the above, MS Edge is the only browser compatible w/ HTTPS-filtering.  But, even _those_ results aren't accurate — AGVPN isn't detected correctly.

**Comment by infinitewaveparticle** [comment]
Was this fixed?
