### ISSUE TITLE
Compatibility mode not working

### ISSUE THREAD

**Issue by Globulopolis** [AdguardTeam/AdGuardVPNForAndroid#172]
Compatibility mode with adguard not working with the latest ag vpn. When I connect to VPN, Adguard just stop protection.

- **AdGuard VPN version:**
  - 2.0.1 b1 (165)
- **VPN mode:**
  - Local VPN
- **Device:**
  - Samsung S9+
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No

### Expected Behavior

Working ag vpn with adguard.

### Actual Behavior

Paused Adguard protection.

**Comment by maxikuzmin** [comment]
Good afternoon @Globulopolis 
Do you have AdGuard compatibility mode selected in both apps?
Try restarting the VPN and select compatibility mode.
Let me know if everything worked out for you

**Comment by maxikuzmin** [comment]
@Globulopolis ping

**Comment by Globulopolis** [comment]
Sorry for delayed reply. I cannot reproduce this issue.

**Comment by maxikuzmin** [comment]
Does that mean the problem is solved? @Globulopolis

**Comment by Globulopolis** [comment]
> Does that mean the problem is solved? @Globulopolis 

Yes.

**Comment by infinitewaveparticle** [comment]
I think this issue is reproducible. It will not work for me.
