### ISSUE TITLE
Selecting Compatibility Mode in AdGuard does not create a SOCKS5 proxy

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdGuardVPNForAndroid#174]
### Issue Details

- **AdGuard VPN version:**
  -  2.0.166
- **VPN mode:**
  -  Compatibility Mode
- **Device:**
  -  Samsung Galaxy S7 Edge
- **Operating system and version:**
  -  Android 8.0
- **Root access:**
  -  No

### Expected Behavior

 Prior to updating AdGuard VPN from 1.x to 2.0.166, selecting Compatibility Mode would automatically create a SOCKS5 connection and enable it.

### Actual Behavior

 Now when selecting Compatibility Mode in both apps no such socks5 proxy is created or enabled. Note: Compatibility Mode seems to function, but prior to the update it would also show the SOCKS5 connection in AdGuard Settings -> Network -> Proxy.

### Screenshots

 I can create a screen recording and email it to you if necessary.

<details><summary>Screenshot:</summary>

</details>

**Comment by maxikuzmin** [comment]
@infinitewaveparticle we have released a new update, please update to version 3.6.8. Check the problem again. Note that you must have compatibility mode selected in both applications, then after enabling Adguard, proxy SOCKS5 should be created automatically.
Please let us know the result.

**Comment by maxikuzmin** [comment]
@infinitewaveparticle ping

**Comment by infinitewaveparticle** [comment]
I'm using 4.0 Nightly 24

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment]
@infinitewaveparticle we have reproduced the situation of deleting a proxy and creating it automatically with compatibility mode enabled and adguard enabled. The proxy is created stably.
Can you please tell me what steps you are reproducing?
You need to select compatibility mode in both applications. 
Open Adguard VPN, select compatibility mode, then you need to connect to any server in the application.
Open Adguard, check the compatibility mode, it must be enabled automatically. Activate the protection of Adguard. 
Done, the proxy server should be created and both applications are working. 
Please reproduce these steps and let me know about your result.

**Comment by infinitewaveparticle** [comment]
Compatibility Mode is enabled in both applications, and it seems to be working... But when I open Settings, Network, Proxy, the proxy is disabled (Off).

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment]
@infinitewaveparticle  usually a proxy is displayed as disabled when you have not enabled the VPN (not connected to any server). Try to connect and check the status of the proxy again
Please reproduce these steps and let me know about your result.

**Comment by infinitewaveparticle** [comment]
It is connected. When I type "my IP" into duckduckgo it gives me the correct AdGuard VPN IP address and location of the server I'm connected to. I think it's actually creating the proxy connection and enabling it - but just not showing it.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment]
@infinitewaveparticle could you send a link on video of your steps?

**Comment by maxikuzmin** [comment]
@infinitewaveparticle ping

**Comment by infinitewaveparticle** [comment]
My steps are literally selecting Compatibility Mode in both apps. I will email the video to devteam in a few minutes.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
Btw, I only check my email once or twice a week

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment]
@infinitewaveparticle we have looked into this issue. Indeed, this problem appears rarely. We are currently working on a solution to this error. Right now unclear what steps are causing it. For now, we recommend rebooting the device, this should help

**Comment by infinitewaveparticle** [comment]
Lol... I seem to always get the rare bugs and errors. Unrelated, but a few rare bugs that were previously fixed have been happening again (crash on enabling WiFi from airplane mode & temporarily not blocking certain Dns user filters when protection restarts after settings change).

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment]
@infinitewaveparticle it seems to be a different problem. I could not reproduce this error, it does not repeat. Please create another issue and also attach the debag logs after the errors. Do you know how send debag logs?

**Comment by maxikuzmin** [comment]
@infinitewaveparticle  issue was closed due to a long time ago. I hope you were able to create another issue and solve the problem

**Comment by infinitewaveparticle** [comment]
I sent the video to devteam. I assure you it is connected to a server.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment]
Honestly I've been using socks 5 mode and haven't checked if the issue still happens or not.

Sent from ProtonMail mobile

-------- Original Message --------
