### ISSUE TITLE
Router web panel is not available via wifi in selective mode

### ISSUE THREAD

**Issue by WhinVader** [AdguardTeam/AdGuardVPNForAndroid#176]
Issue Details

AdGuard VPN version:

v2.1 pre-alpha 3 (20)

VPN mode:

Compatibility Mode

Device:

Samsung Galaxy A40

Operating system and version:

Android 11

Root access:

No

Expected Behavior

The ability to have access to the router web panel when using Wi-Fi (Sercomm RV6699, default web panel address 192.168.1.254) without disabling VPN in regular and selective mode.

Actual Behavior

The web panel is not available initially in both regular and selective mode, however, in regular mode it can be added to exceptions, but in selective mode it is not possible to exclude it from tunneling.

**Comment by maxikuzmin** [comment]
@WhinVader to solve the problem, you can install Adguard, look in the Filtering log where the router goes, exclude all moves in the VPN Exclusions section. For this procedure, you need to have a premium account. If you don't have one, you can take a free trial in the app. 
If that doesn't help, please send the logs. 

Here's what we need to do:

Open the AdGuard VPN app settings;
Advanced settings --> Logging level --> Extreme;
Replay the problem and remember the exact time it occurred;
Open Support --> Export logs and system information;
Send the archive to devteam@adguard.com and include the problem number in the subject line.

**Comment by maxikuzmin** [comment]
@WhinVader did you get it? Please let me know the result

**Comment by WhinVader** [comment]
> @WhinVader did you get it? Please let me know the result

Все запросы к 192.168.1.254 в блокировщике рекламы по дефолту в белом списке, при обычном режиме есть возможность добавить в исключения, а в выборочном режиме не пущает в панель (интересует именно в выборочном режиме)

**Comment by ameshkov** [comment]
Вообще в compatibility mode что именно попадет в VPN-туннель управляется приложением AdGuard. По-умолчанию, приватные подсети (например весь `192.168.1.*`) вообще в туннель не попадают.

А вы low level настройки не меняли?

**Comment by WhinVader** [comment]
> Вообще в compatibility mode что именно попадет в VPN-туннель управляется приложением AdGuard. По-умолчанию, приватные подсети (например весь `192.168.1.*`) вообще в туннель не попадают.
> 
> А вы low level настройки не меняли?

Нет low level настройки и впна и блокировщика сток, ещё такой момент забыл изначально упомянуть, несколько раз были такие моменты когда в выборочном режиме впна была доступна веб панель роутера ,
но в то же время например в приложении youtube переставали отображаться иконки каналов и картинки в постах в сообществе (которые идут через добавленный в выборочный режим yt3.ggpht.com, который заблокирован в рф), но к сожалению не удаётся этот момент с экстремальным уровнем логирования поймать если заранее включать не повторяется, если после проявления приложение тут же отключается от сервера.

**Comment by WhinVader** [comment]
В общем я "поймал" с экстремальным логированием момент когда под впн имеется доступ в веб панель роутера, даже после нескольких смен серверов, но после того как  делаешь отключение от сервера и подключаешься по новой данный момент пропадёт и доступ в веб панель снова недоступен.
Я отправил эти логи на девпочту, с них возможно побольше толку будет чем с первых :)

**Comment by ameshkov** [comment]
Дело в том, что логи нужны будут в том числе и из AdGuard

**Comment by WhinVader** [comment]
> Дело в том, что логи нужны будут в том числе и из AdGuard

Отправил на почту логи и впна и блокировщика.
Где-то в 12:00 запустил логирование, запустил впн и блокировщик, подключился к впн, в веб панель роутера не пускало, не отключая впн и wifi выключил экран телефона, в 12:20 включил, впн был подключён, в веб панель пустило, тест страница adguard впн определила, на заблокированные сайты из выборочного режима пустило, при попытке сменить сервер, впн отключился, после нового подключения веб панель роутера снова стала недоступна.

**Comment by Birbber** [comment]
@WhinVader Hey! We really run all connections along with the main gateways of the router to ensure they are bypassed. Try adding `192.168.1.254` to the exclusions. It should do the job.

**Comment by WhinVader** [comment]
> @WhinVader Hey! We really run all connections along with the main gateways of the router to ensure they are bypassed. Try adding `192.168.1.254` to the exclusions. It should do the job.

Do I understand correctly that you mean exceptions in the vpn app, that are only available in regular mode?

If that's what you meant, then yes, in regular mode, after being added to the exceptions, the router's web panel opens, but I'm interested in how to get access in selective mode.

**Comment by Birbber** [comment]
@WhinVader Yes, I was talking about general mode. As for `selective mode` -- we've created an inner issue on that matter, so please wait till it's fixed.

**Comment by maxikuzmin** [comment]
@WhinVader we started the task, as soon as we finish it - there will be a low-level setting, where you can switch the filtering of your gateway for the selective mode

**Comment by maxikuzmin** [comment]
@WhinVader will be releasing a new version of AdGuard VPN today that fixes your issue. Please update as it comes out and let me know if everything works

**Comment by WhinVader** [comment]
> @WhinVader will be releasing a new version of AdGuard VPN today that fixes your issue. Please update as it comes out and let me know if everything works

it works fine for me :)

**Comment by maxikuzmin** [comment]
@WhinVader great! Closing the issue.
Good luck!
