### ISSUE TITLE
Clearing Phone's Memory ALWAYS Restarts AdGuard Protection

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdGuardVPNForAndroid#179]
### Issue Details

- AdGuard VPN version: 2.0.165
- VPN mode: Local VPN
- Device: Redmi Note 3
- Operating system and version: Android 6.0.1 MMB29M
- Root access: No

### Expected Behavior

1. AdGuard VPN or any of it's processes/activities/service should not be running in the background when all the related settings are disabled (see all settings in Additional Information below).
2. When memory is cleared to close the running apps, AdGuard Protection should not restart.
3. Only when I would like to use the VPN app, I should run it and the device traffic should route through the dedicated server. At other times, when I do not use the VPN app, I would like it to be COMPLETELY disabled.

### Actual Behavior

1. Seems like AdGuard VPN app/some of it's process/activity/service runs in the background even though all the related settings are disabled (see all settings in Additional Information below).
2. When memory is cleared to close the running apps, AdGuard Protection restarts and the VPN component again restarts in the background.
4. When the 'Force stop' button is tapped on the AdGuard VPN app settings page, it should be COMPLETELY disabled and nothing should be running in the background.

### Screenshots

ibb.co/Vm0JWtF

### Additional Information

I have set the following:

1. 'Autostart' setting in phone settings for AdGuard VPN app is disabled
2. The permission "Start in background" is disabled in phone's Permission settings for the app
5. 'Battery Saver' option for the AdGuard VPN app is set to "Restrict background activity" in phone settings
6. 'Force stop' button gets enabled instantly even after tapping on that and trying to close AdGuard VPN app in phone's settings
7. In the 'App settings', the 'AdGuard VPN autostart' setting is disabled
8. 'Watchdog' setting in AdGuard VPN app's Low-level settings is disabled.
9. 'Operating mode' in AdGuard VPN app is set to 'Compatibility mode with AdGuard'

**Comment by Birbber** [comment]
@Nzzyme Hello!
Could you give more info on how you do this point? 
> When the 'Force stop' button is tapped on the AdGuard VPN app settings page, it should be COMPLETELY disabled and nothing should be running in the background.

And also how exactly do you see that some service is running after the app was disable?

**Comment by Birbber** [comment]
@Nzzyme In compatibility mode, AdGuard and AdGuard VPN depend on each other, so when AdGuard VPN process was killed, AdGuard needs to recreate the VPN connection, and it happens on its own.

**Comment by Nzzyme** [comment]
> @Nzzyme In compatibility mode, AdGuard and AdGuard VPN depend on each other, so when AdGuard VPN process was killed, AdGuard needs to recreate the VPN connection, and it happens on its own.

I understand that in Compatibility mode, the 2 apps (AG & AG VPN) work hand in hand and killing the VPN app will restart the AG protection. But that should be true only when running and using the AdGuard VPN app to route the traffic through one of the servers.

At other times, when I would not like to run and use the AG VPN app and when I have disabled all the settings (in phone and VPN app), I would NOT like the VPN app/service/process to be running in the background as it causes this issue whenever the memory is cleared.

On one hand, the VPN app has 2 settings where the user is able to enable and disable "Autostart" and the "Watchdog" but when we disable that, there is no difference in the behavior of the app as it is still running. This means that the settings are just cosmetic and enabling/disabling them has no impact.

I would therefore like to log a bug/enhancement request so that the VPN app should NOT be running in the background when all the settings are disabled.

**Comment by Birbber** [comment]
If you disable `Integration mode` the process shouldn't be started in the background.

**Comment by maxikuzmin** [comment]
@Nzzyme your issue is still relevant?

**Comment by Nzzyme** [comment]
> @Nzzyme when you enable Integration mode, you allow both applications to be used simultaneously (as described in the function description). As mentioned above, the VPN process is restarted precisely because of Integration mode. If you disable Integration mode and close the VPN completely, it will not start up again.

That is what is happening currently but what about the fix to the main problem (AG protection restarting when clearing the phone's memory? I don't have any problem with the VPN app/process/service restarting and running in background. My problem is that when I clear the phones memory, that process is also killed which causes a disconnect.

**Comment by maxikuzmin** [comment]
@Nzzyme is a mechanism of the Android system: to clear files, you need to free the descriptors on them. You can only do that by freeing the process
That's why the application is cleared from memory
