### ISSUE TITLE
Blocks access to the local network

### ISSUE THREAD

**Issue by seazzon** [AdguardTeam/AdGuardVPNForAndroid#183]
### Issue Details

- **AdGuard VPN version:**
  - 2.1 beta 1 (25) (in version 1.2 and 2.0 there was the same problem)
- **VPN mode:**
  - Local VPN. Default all settings.
- **Device:**
  - Redmi 5 Plus
- **Operating system and version:**
  -  Android 9
- **Root access:**
  - Yes

### Expected Behavior

I want to open the router's web interface at http://192.168.8.1/html/home.html

### Actual Behavior

Adguard VPN blocks the opening of this page.
When you disable Adguard VPN, access to the router's web interface is restored.

### Screenshots

<details><summary>Screenshot:</summary>

![vpn-on-off](https://user-images.githubusercontent.com/1830079/170582455-f8e8ff2d-9626-402e-a841-ba198b200e40.png)

</details>

### Additional Information

Change mode (General/Selective): does not matter.
Browser: any (in my case Firefox, Via, Kiwi).
Other Adguard products are not used.

**Comment by Birbber** [comment]
@seazzon Hi! We run all connections along with the main gateways of the router to ensure they are bypassed. Try adding 192.168.8.1 to the exclusions. Let us know the result.

**Comment by seazzon** [comment]
I added the address to exclusions for General and Selective mode.
In General mode, I got access to the router.
In Selective mode, it still blocks access to the router.

P.S. I prefer Selective mode.

**Comment by Birbber** [comment]
@seazzon 
>In Selective mode, it still blocks access to the router.

We've already created an internal issue on that matter. Please wait till it's fixed. 
Also we have similar github issue [#176](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/176), so I'll close this one as a duplicate.
