### ISSUE TITLE
Adguard can't  connect to Samantel Network

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForAndroid#186]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 2.1 beta 25
- **VPN mode:**
  -  local VPN
- **Device:**
  -  sm-g973f
- **Operating system and version:**
  -  12
- **Root access:**
  -  yes

### Expected Behavior

Adguard won't connect on Samantel Network. tried many locations and even changing DNS with all types
### Screenshots

![Screenshot_20220603-185315_AdGuard VPN](https://user-images.githubusercontent.com/40741745/171873786-da07281e-c102-4b91-80d9-1c9a78089aab.jpg)

<details><summary>Screenshot:</summary>

</details>

### Additional Information
[adguard_vpn_logs_2.1.25_0306_185640.zip](https://github.com/AdguardTeam/AdGuardVPNForAndroid/files/8833019/adguard_vpn_logs_2.1.25_0306_185640.zip)
18:56

**Comment by aliafshany** [comment]
Thank you for your response.
Yes, I am aware of the kill switch concept. I had another issue with it, which I was finally able to resolve with Konstantin's assistance.

Here are the Extended Logs you'll need.
The time was 16:00-16:01 when I reproduced the issue.

[adguard_vpn_logs_2.1.34_0606_160105.zip](https://github.com/AdguardTeam/AdGuardVPNForAndroid/files/8844076/adguard_vpn_logs_2.1.34_0606_160105.zip)

**Comment by maxikuzmin** [comment]
@aliafshany rather strangely, none of our requests come with a positive response. Is everything okay with your Internet connection? 
Is it still a problem?

**Comment by aliafshany** [comment]
Hello, @maxikuzmin.
Everything is working properly with my connection, and I have no problems browsing the internet or connecting to "**other** VPN services."

Despite the fact that auto ping is perfectly functional, I am still having issues connecting to AG VPN on this network.

**Comment by maxikuzmin** [comment]
@aliafshany do I understand correctly that with the rest of the VPN Internet connection is stable, and only in our VPN there is no Internet connection and servers do not connect? 
Have you tried reinstalling AdGuard VPN? Let's try reinstalling first, maybe some settings are exposed. 
Let me know the result.

**Comment by aliafshany** [comment]
> @aliafshany do I understand correctly that with the rest of the VPN Internet connection is stable, and only in our VPN there is no Internet connection and servers do not connect? Have you tried reinstalling AdGuard VPN? Let's try reinstalling first, maybe some settings are exposed. Let me know the result.

Yes, you got that right. I can connect to all other VPNs except Adguard.
Strangely, while being able to ping every server, I am unable to connect to either of them.
I've tried connecting on both a Mac and an Android device numerous times, even attempted reinstalling, but to no success.
As soon as I switch to a different data provider on my network, it connects.
It appears that this particular network has blocked access to AG.

I hope you can get around this incredibly irritating restriction.

**Comment by maxikuzmin** [comment]
@aliafshany to troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

Open AdGuard VPN app settings;
Advanced settings --> Logging level --> Extended;
Reproduce the issue and remember the exact time it happened;
Open Support --> Export logs and system info;
Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by aliafshany** [comment]
Hello, @maxikuzmin 
I tried your recommendations once more.

These are the outcomes.

It somehow connected at 18:52 then disconnected in less than 30 seconds.
I repeatedly pushed the "connect" button while trying to reconnect until 18:54.

just sent an email of the logs.

**Comment by maxikuzmin** [comment]
@aliafshany  try to connect to the problematic network and log on to 1.1.1.1 without VPN, and with VPN. 
Let me know if you succeeded in logging. 
If you succeed, please send me extended logs with time info.

**Comment by aliafshany** [comment]
@maxikuzmin hi there
1- without VPN: i can not reach to 1.1.1.1 with this problomatic network althogh with other data provders there is not any problems reaching it ( AG would also work without any problem at those networks )

2- i cannot connect to AG VPN on this network as this issue is about this matter so i can not test it " with VPN". btw i can reach to 1.1.1.1 with other VPNs on this network.

still do you need the logs? eventhough i cannot connect to AG VPN, so no logs recorded during this time.

**Comment by maxikuzmin** [comment]
@aliafshany need  ping 1.1.1.1

- To do this, take a computer 
- Connect to the problem network 
- Open a terminal (on any OS) 
- Enter there ping 1.1.1.1 
- Send us the result

**Comment by aliafshany** [comment]
@maxikuzmin 
is it possible for you to send a test .OVPN connection for me to see if it does connect without any problems, or you cannot?
because I believe it's an AG app issue not the servers.

**Comment by maxikuzmin** [comment]
@aliafshany while we figure it out

**Comment by aliafshany** [comment]
ok then
take your time, thank you

**Comment by maxikuzmin** [comment]
@aliafshany the problem is in the network, there is nothing wrong with our side. In this case I can only recommend to change the network

**Comment by aliafshany** [comment]
@maxikuzmin 
well this is not acceptable to me.
If there is nothing wrong with your side, then why could other VPNs easily connect to this network an AG VPN can't?
For sure there is something to do with your servers.

Please investigate more.

**Comment by maxikuzmin** [comment]
@aliafshany while we figure it out

**Comment by maxikuzmin** [comment]
@aliafshany in the latest nightly version already fixed this. In the beta version should also be fixed. Сheck please

**Comment by aliafshany** [comment]
@maxikuzmin 
yesss it's working noww
thank youuuu🕺🏻

**Comment by maxikuzmin** [comment]
@aliafshany great! Good luck!
