### ISSUE TITLE
Some VPN servers shows Moscow as location

### ISSUE THREAD

**Issue by glomeg132** [AdguardTeam/AdGuardVPNForAndroid#194]
While using Frankfurt (Germany) as a server Google and other pages show Moscow as location. Also some pages are in russion language.

**Comment by Versty** [comment]
@glomeg132 Hi! 

Please make sure you are using general mode and this pages are not added to exclusions. 
Also the browser saves previously visited pages in cache which probably explains pages in Russian. 

I suggest you check one more time using the incognito tab on the [whoer.net](whoer.net).

**Comment by glomeg132** [comment]
Hi, I cleaned the browser cache. In Adguard VPN I use integration with Adguard because I use both (Adguard VPN and Adguard). Also I have no pages in my exclude list. I tried do deactivate Adguard but Google still shows Moscow.

**Comment by glomeg132** [comment]
Seems related to [https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/294](url)

**Comment by Versty** [comment]
@glomeg132 
Seems to be you've experienced temporary issues with servers location detection caused by a hight concentration of Russian users on the same servers. Locations affected: Frankfurt and Helsinki. We are currently working on the fix, servers location will be detected properly soon.

**Comment by aliafshany** [comment]
@Versty 
please add Dublin to the list too
Frankfurt, Helsinki, Dublin

it shows russia

**Comment by Versty** [comment]
@aliafshany Got it! Thank you for noticing.

**Comment by aliafshany** [comment]
@Versty 
please add turkey as well
Dublin is working for me now

**Comment by maxikuzmin** [comment]
@aliafshany @glomeg132 do you have any problems with that now?

**Comment by aliafshany** [comment]
@maxikuzmin 
yes i do
still i see Russian location in google

**Comment by maxikuzmin** [comment]
@aliafshany we're figuring it out

**Comment by artemiv4nov** [comment]
Hello! You see the another location in Google because of Google thinks so, despite the geo-position of the server fact.
The task should be closed.

**Comment by aliafshany** [comment]
@maxikuzmin 
just report the ip here:
https://support.google.com/websearch/workflow/9308722?hl=en

it would solve the issue.
<img width="924" alt="image" src="https://user-images.githubusercontent.com/40741745/233065723-0889d779-3327-486a-9d9a-dc1b7b5712ff.png">
