### ISSUE TITLE
in-app update fails 

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForAndroid#195]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 2.1(50)

- **Device:**
  - SM-G973F
- **Operating system and version:**
  - Android 12
- **Root access:**
  - yess

according to this (https://t.me/adguarden/490) post on Telegram, I should have received the beta version so much earlier than Google play version.
now, I don't have GP update yet because of regional releasing new versions, and also, AG didn't download the new beta ( AdGuard VPN 2.1.1 (beta 1)) on its own.

wish there was a button in order to check new updates manually

**Comment by Versty** [comment]
@aliafshany 
Auto-updates mentioned in the Telegram post works only with new release versions which will be available soon. AdGuard VPN 2.1.1 beta-1 is a beta version and you can update manually or via the GP store if you joined as a [beta tester](https://uploads.adguard.org/Screenshot_20220802-142512_Google_Play_Store.png).
