### ISSUE TITLE
AdGuard Forum Account not be approved since last year

### ISSUE THREAD

**Issue by BruceGeng2012** [AdguardTeam/AdGuardVPNForAndroid#197]
Hi,
    Can your guys kindly check my AdGuard Forum Account status…Since last year up to now, my account still showing this as below,

    _Your account is currently awaiting approval by an administrator. You will receive an email when a decision has been taken._

    Was trying email the support team and leave message from AdGuard app, but still the same.

    So is there any one can give me a big hand?

    Kindly hope your respond, thanks a lot….

Bruce

**Comment by Alex-302** [comment]
Hi. Please check again.

**Comment by BruceGeng2012** [comment]
Hi Alex,
    I checked it out at the forum. Now it's working, I can make a comment and new posts.
    Thanks a tons. 
    Hope u a wonderful day.

Bruce
