### ISSUE TITLE
Problems Activating Proxy Settings

### ISSUE THREAD

**Issue by rubeng70** [AdguardTeam/AdGuardVPNForAndroid#2]
in the blog page the author says:

Go to Settings — Advanced — Low-level settings — pref.excluded.packages and be sure that the option contains the com.adguard.vpn line at the end. If it doen’t exist, please, append it to the end.

**Question: I do not see "com.adguard.vpn  at the end" in the options in Low-level settings???**

Go to Settings — Net — Proxy and add the new one proxy with the IP address 127.0.0.1 and the 1080 port. You can check whether the connection works by tapping the button at the bottom of the dialog.

**Comment: I configured a new proxy with settings (HTTP 127.0.0.1 port 1080 and then "proxy connection is not working"**

Final: I used another proxy configuration "SmartDnsProxy" and "surprise It Works"

Please Help me with the integration

**Comment by jason1208419** [comment]
Question: I do not see "com.adguard.vpn at the end" in the options in Low-level settings???

Click on Settings — Advanced — Low-level settings — pref.excluded.packages 
go to the bottom and in a new line, add com.adguard.vpn

To developers
I follow all the config state on the web and only mobile data work. When I connect to WIFI, it state Proxy is disabled. When I click connect, it state Connecting -> Reconnecting -> Proxy is disabled
I think it's a bug. Please fix it.

**Comment by ameshkov** [comment]
Here's how it should look like:

https://uploads.adguard.com/pref_exclusions.png

**Comment by Get09** [comment]
Тоже не работает.
Создал прокси IP127.0.0.1 порт 1080. В низкоуровневых проверил запись:com.android.providers.downloads.uicom.adguard.vpn
com.adguard.vpn . Проверяю соединение: "Не удается подключиться к прокси".

**Comment by jason1208419** [comment]
> Question: I do not see "com.adguard.vpn at the end" in the options in Low-level settings???
> 
> Click on Settings — Advanced — Low-level settings — pref.excluded.packages
> go to the bottom and in a new line, add com.adguard.vpn
> 
> To developers
> I follow all the config state on the web and only mobile data work. When I connect to WIFI, it state Proxy is disabled. When I click connect, it state Connecting -> Reconnecting -> Proxy is disabled
> I think it's a bug. Please fix it.

Thanks developer. My proxy mode work fine now on my WIFI in version 1.0.111
