### ISSUE TITLE
AdGuard VPN can't connect to the selected server because the server is not responding

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForAndroid#204]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
- 2.2 beta 1.1 (18)
- **VPN mode:**
  Local VPN
- **Device:**
  - sm-g973f
- **Operating system and version:**
  - Android 12
- **Root access:**
  - Yes

### Actual Behavior

- pressing every server/location results in that error.
- I recorded a video.
i don't think it's relate to the Iranian Gov. because i can connect on my mac without any issues.
btw, logs are sent already to this email : `devteam@adguard.com`

### Screenshots

https://user-images.githubusercontent.com/40741745/194700289-4a89501c-0e03-441b-9087-0e2e41b4fe6c.mp4

**Comment by Versty** [comment]
Hi, @aliafshany! 
We've done a quick check of the logs, everything points to blocking by government .
Could you also send logs from your Mac so we can compare and possibly fix it?

**Comment by Versty** [comment]
@aliafshany 
Do you need to use other VPN every time you re-launch AdGuard VPN?

**Comment by aliafshany** [comment]
@Versty 
these days that the gov. has restricted AG, yes I do need it on mac.
but let me tell you something. it seems that the restriction is changing all the time. for example, i can not connect to any of the locations, although I could the day I opened this issue.

**Comment by Versty** [comment]
@aliafshany Sad to hear this news. 
In that case we need new debug logs from your Mac device, could you collect it and send one more time, please? 
(with the issue of connecting to locations)

**Comment by aliafshany** [comment]
@Versty 
sure i can do it

I will send it in a few minutes later.

**Comment by aliafshany** [comment]
@Versty 
12:54 i opened AG with the help of another VPN.
12:54 i tried to connect to Italy but it stuck at the connecting window.
12:55 tried to connect to berlin
and then i quit.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/40741745/195052527-9b221cf2-b226-4c7a-b9a8-806c6747cf73.png">

**Comment by MH140000** [comment]
hello, i have this problem. if you want, i can send log. Since yesterday, adguard vpn servers are not loaded and the message location not found is seen. This problem is on both Android and Windows.

**Comment by MH140000** [comment]
I sent logs with Android OS to devteam@adguard.com.

**Comment by Versty** [comment]
@MH140000 The issue is related to blocking by the Iranian government. We have enough information, but thanks for your suggestion! 
@aliafshany So, unfortunately, it is not a bug or some application issue. 
AdGuard team stands with Iranian people and strongly support freedom and rights for any nation to have non-restricted internet access. We hope that everything will get better as soon as possible.

**Comment by MH140000** [comment]
Hi. Yes, i know
I bought this service please solve

در تاریخ سه‌شنبه 11 اکتبر 2022،‏ 16:31 AdGuard GitHub Bot <
***@***.***> نوشت:

**Comment by Versty** [comment]
@MH140000 We are currently looking for a solution.
Also, you can contact [AdGuard VPN support](https://adguard-vpn.com/en/support/apps.html) and ask for a refund.

**Comment by aliafshany** [comment]
@Versty 
hey Diana I truly appreciate what you said. You are a very thoughtful and nice person.
I also appreciate the effort you and your team are doing to get around this restriction. I wish you luck in finding a solution.
well done

>@aliafshany So, unfortunately, it is not a bug or some application issue. AdGuard team stands with Iranian people and strongly support freedom and rights for any nation to have non-restricted internet access. We hope that everything will get better as soon as possible.

**Comment by MH140000** [comment]
> @MH140000 We are currently looking for a solution. Also, you can contact AdGuard VPN support and ask for a refund.

I bought this software from a dealer, so the support said that we cannot refund the amount. We look forward to solving the problem.

**Comment by MH140000** [comment]
Hello. In the latest beta version, the locations are loaded, but when I click connect, nothing happens and it stays disconnected.
