### ISSUE TITLE
crash when you press disconnect button

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdGuardVPNForAndroid#205]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - Latest beta
- **VPN mode:**
  - Local VPN
- **Device:**
  - SM-G973F
- **Operating system and version:**
  - Android 12
- **Root access:**
  - Yes

### Expected Behavior

app crashes when you
1- connect to a location
2- then you press disconnect ( it doesn't matter if it is connected or you press in the middle of connecting)

### Screenshots

https://user-images.githubusercontent.com/40741745/195569477-16d1631e-c8c3-4acc-85f2-17d056ed74a6.mp4

### Additional Information

Logs are sent

**Comment by MH140000** [comment]
This service is blocked in many ISPs in Iran. please help.

**Comment by aliafshany** [comment]
@MH140000 
are u asking help from me?
well AG devs should help you not me, and tbh they are doing what they can to bypass the restriction.

دولوپر ها در حال تلاشن تا مشکل رو حل کنن, از دستشون خارج هست در حال حاضر ولی در حال تلاشن.

**Comment by Versty** [comment]
@aliafshany Hi! 
Currently investigating logs from your device, seems like rare bug. 
Has this issue occurred since yesterday or have you seen it before? 
Also, how often does it reproduce, for example, how many crashes have happened out of 10 attempts?

**Comment by MH140000** [comment]
@aliafshany Yes I know I just asked the dev team.

**Comment by Versty** [comment]
@aliafshany Could you please answer my questions above?

**Comment by aliafshany** [comment]
@Versty 
i am sorry for the delay.
These days college takes a lot of time.

i have had this issue since the release of the latest beta.

10/10 attempts have resulted in a crash.

**Comment by maxikuzmin** [comment]
@aliafshany please try updating to version 2.2 
Let me know the result

**Comment by aliafshany** [comment]
@maxikuzmin 
i am using v2.2 rc 29 currently.
the result is the same

**Comment by aliafshany** [comment]
@maxikuzmin 
it is totally fixed for me now

Thank you
