### ISSUE TITLE
Indian vpn server speed is slow

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdGuardVPNForAndroid#212]
Hi,

I am using your adguard vpn with adguard adblocker, so both are switched on, but for last two weeks indian server time become more than 200ms, I living in Bangalore and vpn server is in Bangalore so vpn application suppose to shows time as 5 to 10 ms, but for two weeks it shows 200 ms, so speed drop drastically. Everytime it says japan or Germany is the nearest and speedest server available, it is another side of the world and speed drops very badly whenever I choosen these servers.

Mobile: OnePlus 6t
Rom: custom rom name crdroid 9 (basrd on Android 13)
Root is available using magisk canary version
Adguard adblocker version is 3.6.10 
Adguard vpn version is 2.2(36)

![Screenshot_20221030-002047_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/198848193-6bd3cb0f-148e-4b2f-b3e7-4e8ab52097c9.png)
![Screenshot_20221030-001935_AdGuard.png](https://user-images.githubusercontent.com/97349871/198848215-62e11881-ae1f-4550-bd47-c7eacd5505b0.png)
![Screenshot_20221030-002439_Alpha.png](https://user-images.githubusercontent.com/97349871/198848263-34e2ced0-d8f2-437a-8682-48c66b4b1b10.png)

![Screenshot_20221030-002511_Settings.png](https://user-images.githubusercontent.com/97349871/198848366-ab2921a3-37a8-484b-9761-7a60fa8aee36.png)

![Screenshot_20221030-002907_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/198848486-f69fdc7a-bc1e-463b-9142-d32299b11467.png)

**Comment by maxikuzmin** [comment]
@kumar041 did I understand correctly that the speed is fine as long as Germany or Japan are not offered as faster servers? As long as this does not happen, the speed is always fine on India location? Do you switch to Germany or India when doing this, or does the speed drop even without changing locations?

**Comment by kumar041** [comment]
Hi,

Seriously my near by servers india, Singapore, combodia, South Africa, servers are very busy. I have to answer to your question vpn application says german and japan servers are free, sometimes i don't want to believe London server is free, sometimes even Russian servers are free, so I am asking there should be anyone of the nearby server should be free, but all of them are very busy. I have attached some screenshots for your reference kindly tell me what to do, should i connect to russia or japan or germany.
![Screenshot_20221031-181500_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/199011192-501f60ba-c7c2-483b-bc42-06a260f1e7cc.png)

![Screenshot_20221031-181454_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/199011249-7579822c-9f13-4a7b-99d5-8bb932196e71.png)
![Screenshot_20221031-181442_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/199011326-603a2c33-cfe1-4a98-9b2b-fc4c5cb762fa.png)

![Screenshot_20221031-181414_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/199011393-8c8d782b-8703-4878-af77-45997cc2996f.png)

**Comment by kumar041** [comment]
Hi,

Sorry to say this yes I don't know how vpn servers and load balancing is work, also as per your response ping from my mobile to Bangalore server is more than that of japan then I need to use japan server, so I have to use distance server rather than my neighbourhood server. As well as I like to use Indian server only that's why I had purchased your vpn.
