### ISSUE TITLE
Integrated mode does not work 

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForAndroid#218]
I am unable to use AdGuard VPN together with AdGurd

AdGurd VPN version: 2.3  pre-alfa 1
AdGurd: 4.0 nightly 23

![Screenshot_20221113-104703_AdGuard VPN.jpg](https://user-images.githubusercontent.com/16819380/201526037-fee7f168-8dd5-4a5b-9477-26e155603033.jpg)

**Comment by AlfredSpijker** [comment]
https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/210

**Comment by maxikuzmin** [comment]
@eduardoaddad these versions don't match right now. Wait for a new version or download an older version
