### ISSUE TITLE
Changing «Routing» causes app crash

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/AdGuardVPNForAndroid#22]
### Prerequisites

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 1.0.155
- **VPN mode:**
  - Integration with AdGuard
- **Device:**
  - Huawei MediaPad M5 Llite 10
- **Operating system and version:**
  - Android 8.0
- **Root access:**
  - No

### Expected Behavior

Successful change of Routing from Integration with AdGuard to SOCK5

### Actual Behavior

App crash

### Video

<details><summary>Video:</summary>

In a Jira ticket.

</details>

**Comment by admitrevskiy** [comment]
This issue will be resolved in the next release
