### ISSUE TITLE
Pink

### ISSUE THREAD

**Issue by Sarang1990** [AdguardTeam/AdGuardVPNForAndroid#226]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no 

> answer

- [x] I checked to make sure that this issue has not already been filed

**Comment by Sarang1990** [comment]
متاسفانه به صورت سهوی delete account کردم . بعد این اتفاق دیگر وصل نمیشود . سرور را نمیشناسد

**Comment by Sarang1990** [comment]
```
Tokens
VPN token: updating...
Credentials: 
  auth token: updating...
  expiration time: updating...
  expiration time, sec: updating...
  license status: updating...

Device
username: —
applicationId: —

Current endpoint
id: —
country: —
city: —
premium only: —
ping bonus: —
domain name: —
connected IP address: —

Connection status
transport mode: Vpn
last connection at: —
data received: —
data sent: —
estimate RTT: —
estimate packet loss: —
protocol: —

```

**Comment by Versty** [comment]
@Sarang1990 This issue is caused by your ISP blocking certain services due to government restrictions. 
Please contact our customer support if you have any further questions. 
`support@adguard.com`
