### ISSUE TITLE
Trouble with authorization.

### ISSUE THREAD

**Issue by vladimirov-s** [AdguardTeam/AdGuardVPNForAndroid#227]
- version 2.2.40
- I checked to make sure that this issue has not already been filed

 I enter my email/password and touch login. Application reports me about some mistakes, and try to do it later. 
What is a problem?
Thanks.

- **AdGuard VPN version:**
  - 2.2.40
- **VPN mode:**
  - local
- **Device:**
  - Realme GT neo 2T
- **Operating system and version:**
  - Android 12
- **Root access:**
  - No

### Expected Behavior

after enter email I must enter password 

### Actual Behavior

Some mistake happens.

### Screenshots

I attached the screenshot

### Additional Information

![Screenshot_2022-12-04-22-24-44-63_af0b5dda1a8302ea8cf6b58caed91d49](https://user-images.githubusercontent.com/101799674/205511103-e9bef9f4-9095-489d-b937-ebbfabe07237.jpg)

**Comment by vladimirov-s** [comment]
Solution was found. 
For experimental purposes, in the VPN settings, I previously checked the box to block unfiltered connections. A lot of apps stopped working. I did not immediately understand the reason. Removed the daw, everything was fine.
![IMG_20221204_232841](https://user-images.githubusercontent.com/101799674/205514620-a8bec6b0-4717-42d8-9f0f-486cdc2d2be4.jpg)

**Comment by ameshkov** [comment]
Yeah, kill switch with integration mode is more trickier than that, see here: #110
