### ISSUE TITLE
Google Play Android version number mismatch?

### ISSUE THREAD

**Issue by snhv** [AdguardTeam/AdGuardVPNForAndroid#239]
The current version on the Google Play Store is 2.2.40 which is actually 2.2.1.40 whereas the latest version is 2.2.2
Could this be the reason why 2.2.2 is not updated on Play Store?

**Comment by artemiv4nov** [comment]
There are two versions: technical version which is shown in Play Store, and an official version which is shown inside the app. Please do not compare them.
