### ISSUE TITLE
Dns leak question

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdGuardVPNForAndroid#240]
Hi,

I am using your adguard adblocker with your vpn application on android 13. My doubt is when I select cloudflare dns and connect to your vpn then there will any dns leak will happen, if I select any other dns server apart from adguard it will be there any security risk involved. I try to understand in here is when I am using vpn connection whatever default dns server there are providing I need to use it for any security reason. Orelse I can choose any other dns server in your adguard application. Kindly provide any faq or else any knowledge base so I can read and understand this concept.

Thanks and regards,
Rajkumar

**Comment by maxikuzmin** [comment]
@kumar041 we are working on it. I'll be back later with an answer to your question

**Comment by maxikuzmin** [comment]
@kumar041 it's done! You can read about DNS leak [her](https://adguard-vpn.net/kb/general/dns-leaks/) :)
