### ISSUE TITLE
Can U add Custom AdGuard DNS in Google TV AdGuard Android VPN App

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#241]
AdGuard VPN for Android is already available on the google TV 4K streaming stick so I was hoping you guys could add the custom AdGuard private dns in the AdGuard vpn app on the google tv 4K streaming stick. 

Right now it uses the AdGuard non-filtering DNS on the google tv 4K streaming stick.

**Comment by maxikuzmin** [comment]
@Batman2814 yes, of course. AdGuard VPN for Android will repeat the functionality of the mobile version in the future. Just need a little patience and we will gradually add the missing functionality :)

**Comment by maxikuzmin** [comment]
@Batman2814 for the moment, I’m closing this issue. Please wait for the following updates
