### ISSUE TITLE
AG VPN — private proxy product name is missing for localization

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForAndroid#244]
`AdGuard VPN — private proxy` string missing for localization (Crowdin) on the Google Play.

<details><summary>Google Play</summary>

![image](https://user-images.githubusercontent.com/35523759/213008537-b8a9a4da-cd9f-40dc-8688-13ea557a0e42.png)
</details>

<details><summary>Crowdin</summary>

![image](https://user-images.githubusercontent.com/35523759/213008747-b767955e-afcb-46dc-8d21-df1800bc629c.png)
</details>

**Comment by Versty** [comment]
@gork7777 Hi! 
We are currently using this string for the store search optimisation, so it is intended to not be available for translation in Crowdin.
