### ISSUE TITLE
Compability mode is not available in settings 

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdGuardVPNForAndroid#245]
Hi I am using your adblocker and  beta version of your vpn together, but yesterday I have updated through play Store now compability mode options is not available in vpn application settings, so what should I do now, if I want to use vpn with adblocker, i don't know how to set it together, can you update your vpn application or just tell me how to use them together.

Adguard adblocker

![Screenshot_20230131-152054_AdGuard.png](https://user-images.githubusercontent.com/97349871/215726855-fdca0272-f059-47df-a6d2-c69da9c79237.png)

![Screenshot_20230131-152028_AdGuard.png](https://user-images.githubusercontent.com/97349871/215726913-f495185d-585e-40ae-99f1-ad04e82f25eb.png)

Adguard vpn

![Screenshot_20230131-152105_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/215726996-a2b595ea-e814-40a5-9cc4-da2a1bbc4a8b.png)

![Screenshot_20230131-152131_AdGuard VPN.png](https://user-images.githubusercontent.com/97349871/215727025-a40df1e3-09f3-4738-b1bb-f994b4f8c04c.png)

**Comment by Versty** [comment]
@kumar041 Hi! Thank for the feedback! 
What happens if you click the Upgrade button?

**Comment by kumar041** [comment]
Nothing happens I am already using beta version of your vpn application, so what should I update to, if possible please provide nightly build, i like to try it out.

Thank you,
Rajkumar ![Screenshot_20230131-161703_Google Play Store.png](https://user-images.githubusercontent.com/97349871/215739608-7456f752-84b4-44c6-8398-6750a441788b.png)

See I am already using beta version of your vpn

**Comment by kumar041** [comment]
![Screenshot_20230131-163014_Vivaldi Browser Snapshot.png](https://user-images.githubusercontent.com/97349871/215742534-50a54fcc-90d2-456d-b6e0-9bc9d19b9bd0.png)

It is asking me to join beta program which already i have, next what to do

**Comment by Versty** [comment]
@kumar041 This time you should apply to join the "Nightly" testing program, which is different from beta. 
Please follow the instructions on the page.

**Comment by kumar041** [comment]
Hi,

I have joined already but I am not able to download the nightly, so tell me how to download from the google group.

**Comment by Versty** [comment]
@kumar041 Please wait a little, if you have applied correctly, the download in the Google Play will appear soon. 
Detailed explanation will be available in [the AdGuard blog](https://adguard.com/en/blog/index.html) soon!
