### ISSUE TITLE
[Nightly] AdGuard 4.0 + AdGuard VPN 2.3 Integration mode

### ISSUE THREAD

**Issue by phre2** [AdguardTeam/AdGuardVPNForAndroid#249]
I've already issued the problems via Telegram, but I thought via GitHub would have been better for you guys and for other users facing the same.

Yesterday I updated to both nightly versions of AdGuard and VPN and noticed that when VPN is on, it brokes DNS filtering and switches to my ISP DNS.

![Screenshot_2023-01-31-11-58-42-708_com.android.chrome.jpg](https://user-images.githubusercontent.com/96545137/215853565-0809dcb8-1f71-4ad8-b593-e7c7712264ed.jpg)

![Screenshot_2023-01-31-11-59-26-194_com.android.chrome.jpg](https://user-images.githubusercontent.com/96545137/215853587-f8b404e5-d6b0-43ed-b59f-fff9392b9590.jpg)

Also, but I don't know if that's actually an issue, I noticed that when turning on VPN, AdGuard doesn't switch anymore to proxy mode, but somehow still works.

**Comment by Versty** [comment]
@phre2 Hi! Thanks for the nightly feedback!

> Also, but I don't know if that's actually an issue, I noticed that when turning on VPN, AdGuard doesn't switch anymore to proxy mode, but somehow still works.

This behaviour is intended. 



> Yesterday I updated to both nightly versions of AdGuard and VPN and noticed that when VPN is on, it brokes DNS filtering and switches to my ISP DNS.

Could you check whether this issue reproduces on the latest nightly? (4.0 nightly 45)

**Comment by phre2** [comment]
Yes, I'm on the latest nightly and the issue is still there.

**Comment by Versty** [comment]
@phre2 We are investigating this issue. 
Although you are the first who found this issue, it would be more convenient to discuss it further in #251. 
Please, join!
