### ISSUE TITLE
Making notification a persistent one

### ISSUE THREAD

**Issue by LordSithek** [AdguardTeam/AdGuardVPNForAndroid#256]
### Issue Details

I think it was like that before but I may be wrong... Anyway, I think it would be better to make app's nofication showing connection status a persistent one. I often dismiss all non-persistent notifications at once and AdguardVPN notification is being dismissed as well. Then I start to wonder if the connection is still there or not.

### Proposed solution

Making connection status notification a persistent one

**Comment by Versty** [comment]
@LordSithek Currently the notification is persistent if AdGuard VPN is connected to the location. And non-persistent if it is disconnected. 

If this feature request will be liked enough by other users, we will reconsider the behaviour of the notification.

**Comment by artemiv4nov** [comment]
Since Android 13, there is no longer persistent notifications. I don't think this functionality could be useful in the future
