### ISSUE TITLE
[Question] Can you give extra data for Turkey?

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForAndroid#257]
### Issue Details

Social media also has speed problems and restrictions have been imposed. Most users can overcome this with just a VPN. Can you give at least 1 or 2 GB extra data for support to Turkey or open Turkey location for a while without premium for for users in Turkey? Some other VPNs did this too.

**Comment by Versty** [comment]
@gork7777 We are currently providing direct help, and yes, we will add more free GB for users in Turkey very soon.

**Comment by gork7777** [comment]
@Versty Hm I guess 10 GB was added, right? Thanks for your help!
