### ISSUE TITLE
Mobile Data DNS Leak

### ISSUE THREAD

**Issue by loca-lhost** [AdguardTeam/AdGuardVPNForAndroid#258]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3 Alpha 1

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 12
- Device:Note 11 Pro 5G
- Firmware:MIUI
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

On wifi there's no dns leak. But on mobile data there's a leak and adguard dns page doesn't show connected when you try checking. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@loca-lhost Hi! 
Could you specify the DNS server you are using?
