### ISSUE TITLE
Google does not download Nightly version, only beta version to my devices and I'm a registered Nightly tester.

### ISSUE THREAD

**Issue by Ger2Git** [AdguardTeam/AdGuardVPNForAndroid#259]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Nightly

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 11
- Device:Both Moto G Power(2020) and Nvidia Shield Pro(2019) TV
- Firmware:Irrevallent
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Over several weeks ago I registered as a VPN  Nightly tester and was approved.
2 Went to Google Play and Requested that they download the Nightly version of the VPN,
3. They said soon (it has been almost four weeks now) they keep downloading the Beta Version of the VPN, not the Nightly version.
4. How do I resolve this issue?
5.  What else do you need to resolve this issue?

### Expected Behavior

I expect to be able to get a direct link to the Nightly version, by passing google since they can't or won't get with the program.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@Ger2Git Please send the email to the `devteam@adguard.com` from the same email you have been registered for nightly. 
Mention `#259` number in the subject line. We will check you application.

**Comment by Versty** [comment]
@Ger2Git Have you sent the email?

**Comment by Versty** [comment]
@Ger2Git Closed due to no reply.
