### ISSUE TITLE
Adguard VPN only shows 5 devices instead of 10

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#261]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Adguard VPN Android Nightly

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 13
- Device:Samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.open Adguard VPN
2. Go to settings
3.go to license 

### Expected Behavior

It's showing you can have up to 5 devices simultaneously using Adguard VPN but you guys changed the limit to 10 devices simultaneously to use Adguard VPN at the same time.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![Screenshot_20230303_141022_AdGuard VPN](https://user-images.githubusercontent.com/96619913/222821257-b83be980-ab03-4d57-ad6b-31f872118b43.jpg)

**Comment by Batman2814** [comment]
![Screenshot_20230303_141022_AdGuard VPN](https://user-images.githubusercontent.com/96619913/222821456-53948b0a-c703-48e1-b741-edde30d9012f.jpg)

**Comment by maxikuzmin** [comment]
@Batman2814 thank you! We'll be sure to fix that
