### ISSUE TITLE
Adguard VPN Nightly for Android TV keeps disconnecting

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#265]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Version 2.3 Alpha 1 (24)

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS: Android 13
- Device:Samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Adguard for Android is enabled
2. I connect Adguard VPN
3. when I come back to Adguard VPN after a while it's disconnected 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I have Adguard VPN Nighly Integrated with Adguard for Android Nightly so whenever I have Adguard VPN on while Adguard for Android is on the Adguard VPN Nightly disconnects after a while when I come back from it shows that Adguard VPN nightly is not enabled.

**Comment by maxikuzmin** [comment]
@Batman2814 do you have compatibility mode set up?
This can happen due to loss of network. Is this happening when using a mobile network?
It would be nice to catch this and have at least an approximate time of Adguard VPN disconnection. Choose "Extended logs" in advance so you can upload them later and send them to us.
I'll also observe this.

**Comment by Batman2814** [comment]
How do I do that on the Google TV 4K streaming device from Google where Adguard VPN for Android is also available?

**Comment by maxikuzmin** [comment]
@Batman2814 how often does the problem occur? I haven't been able to reproduce this problem yet

**Comment by Batman2814** [comment]
Need more time using Adguard vpn on my Google tv to test it more. Haven't been watching anything with it on lately as I've been busy. Should be able to let you know this month.

**Comment by Batman2814** [comment]
So far, it is staying connected when I used it today. Let me give it a few more tries this week, and if it is still staying connected, I will close this issue myself.

**Comment by Batman2814** [comment]
I have been using Adguard VPN Nightly for Android on my Google TV 4K Streaming Stick all weeks and so far the VPN is staying connected on Version 2.3 Nightly 1.
So, I'm going to close this issue report.

**Comment by maxikuzmin** [comment]
@Batman2814 great news!
