### ISSUE TITLE
Prime Video is able to detect Adguard VPN for Android on Google Google TV Streaming Stick on U.S Server 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#268]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Adguard Nightly 2.3 Nightly 1

### Operating mode

VPN

### Environment

```markdown
- OS:Android TV OS Version 12 
- Device:Google Google TV 4K Streaming stick
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Put Adguard VPN on a US server 
2. Open Prime video
3. You get a message saying something went wrong. We were unable to load your profiles at this time press okay to go home

### Expected Behavior

Take you to US Prime video where you will see the home screen.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I did troubleshooting steps like clear cache, which didn't fix the problem. Also, I tried another VPN like surfshark VPN, and I was able to get the U.S. Prime video on the Google TV 4K Streaming stick.

**Comment by Batman2814** [comment]
This is just an update just tried accessing the U.S Prime video with Adguard VPN Nightly for Android. I'm still not able to access it. Getting error messages saying "Something went wrong" or "We're unable to load your profiles at this time. Press ok to go to Home".

**Comment by Batman2814** [comment]
I'm not getting the error message since the updated release of Adguard VPN for Android Nightly but I'm not able to play the movie that is on US Prime Video where it says we've detected you are using a VPN or proxy please disable it. I don't have this problem with Surfshark VPN so if you can fix this issue in Adguard for Android Nightly so I can watch US Prime Video.

**Comment by maxikuzmin** [comment]
@Batman2814 thanks for the long wait! As far as I know, we fixed this behavior in May. Is it still recurring?

**Comment by Batman2814** [comment]
Yes, it is still recurring. I get a message saying “Your device is connected to the internet using a VPN or proxy service. Please disable it and try again. For more help, go to prime video.com/vpn.”

**Comment by maxikuzmin** [comment]
@Batman2814 we checked with Seattle, Denver and New York locations. There is no such error. What location are you using?

**Comment by maxikuzmin** [comment]
@Batman2814 we are checking it out, we need some time to figure it out. Please wait a bit

**Comment by maxikuzmin** [comment]
@Batman2814 thanks for waiting! I checked now, Prime Video is working correctly with AdGuard VPN on US location.
Please check it for yourself. It will be better to upgrade to version 2.5 beforehand. Let me know the result

**Comment by Batman2814** [comment]
It is working on New York. But the Atlanta server is not working. it's able to detect VPN. It's not the first time Atlanta server has had problems. Atlanta server was also having problems in the Bing App theat uses chat gpt 4 on mobile, where I also reported it.

**Comment by maxikuzmin** [comment]
@Batman2814 I suspect you might have gotten back on the IP that Prime detects. I've already written about that [here](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/255#issuecomment-1572353266).
I haven't had this happen again, connecting to Atlanta, Prime does not detect my VPN connection.
Try restarting the app or changing the location to another US location, this will allow you to connect to a different IP that won't detect Prime. Unfortunately, this can happen sometimes, so you just need to reconnect or change the location to a neighboring one.
For the moment, I'm closing this issue
