### ISSUE TITLE
Adguard VPN Nightly is disconnecting

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#269]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Version 2.3 Nightly 1

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 13
- Device: Samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Batman2814** [comment]
Logs have been sent

**Comment by Versty** [comment]
@Batman2814 Please provide details on this issue.

**Comment by Batman2814** [comment]
On my phone when Adguard VPN Nightly is on and Integration with Adguard for Android Nightly the VPN disconnects. while searching while surfing in my browser when reading articles Adguard VPN disconnects and I have to enable it myself again so many times.

**Comment by Versty** [comment]
@Batman2814 Are both applications set up for integration? 
Make sure the `Integration with AdGuard VPN` option is enabled in AdGuard. *Protection -> AdGuard VPN*
Then launch AdGuard VPN and check if the Operating mode set to `Integration with AdGuard`. *Settings -> App settings -> Advanced settings -> Operating mode*

**Comment by Batman2814** [comment]
yes, it is set to that.

**Comment by Versty** [comment]
@Batman2814 Please update Adguard For Android to the latest nighty version. 
Then run both apps in Integrated mode, wait for the issue to be reproduced and remember the exact time. 
Collect the logs of both apps and send them to `devteam@adguard.com`, mention the number `#269` and the time when the issue occurred.

**Comment by Batman2814** [comment]
I am already on the latest Nightly build for Adguard VPN for Android and have already sent the logs. Why are you asking me to do it again? Did you not find what the problem was in the last logs I sent you?

**Comment by Batman2814** [comment]
Logs have been sent

**Comment by Batman2814** [comment]
Sent another log file today.

**Comment by Batman2814** [comment]
logs have been sent again

**Comment by Versty** [comment]
@Batman2814 Thank you for your efforts, we are examining the logs.

**Comment by Versty** [comment]
@Batman2814 Does the issue persists in Adguard VPN 2.3 nightly 4? 
We have made some adjustments in the latest nightly, which may fix the issue.

**Comment by Batman2814** [comment]
The issue is still in Nightly 4. I sent logs on that version.

**Comment by Batman2814** [comment]
The issue is still in Nightly 5. Adguard VPN Nighlty is even disconnecting on my Google TV 4k streaming stick when watching Netflix and also happening on my phone.

**Comment by Versty** [comment]
@Batman2814 Thank you for the new log archives. We keep working on this issue.

**Comment by Batman2814** [comment]
Sent new logs on Adguard Version 2.3 Nightly 8 just released this update, and Adguard VPN for Android is still disconnecting.

**Comment by Batman2814** [comment]
So far when updating Adguard VPN for Android Nightly Version 2.3 Nightly 10 it's been staying connected. I haven't seen it disconnect so does that mean you addressed the issue?

**Comment by Versty** [comment]
@Batman2814 We have made some adjustments. Has the issue resolved on your device?

**Comment by Batman2814** [comment]
AdGuard VPN for Android Nightly on my Google TV 4K Streaming Stick keeps disconnecting when watching Netflix which is on version 2.3 Nightly 18 so there is still a need for improvement. I cannot send logs from my Google TV 4K Steaming stick because there's no way to do it from that device.

**Comment by Batman2814** [comment]
Logs have been sent again.

**Comment by Versty** [comment]
@Batman2814 Something clearly went wrong with VPN on your device. AdGuard VPN application may be stoped by the system or crashed. To know what exactly has happened, we need to examine the system bug report from your device. 

Please, wait for the issue to be reproduced, then collect the system bug report as described [here](https://adguard.app/kb/adguard-for-android/solving-problems/logcat/#capture-a-bug-report-from-a-device).
Send the file to `devteam@adguard.com`, mention in the subject line the `269` number and the reproduction time.

**Comment by Versty** [comment]
@Batman2814 Does the issue still persist?

**Comment by Batman2814** [comment]
AdGuard VPN keeps disconnecting on my phone and Google's TV 4K Streaming stick when watching Netflix. I'm waiting to catch it on my phone for the logs, but for the Google TV 4K streaming stick, there's no way to do it. As soon as I catch it on the phone, I'll send the logs.

**Comment by Batman2814** [comment]
Logs been sent

**Comment by Versty** [comment]
@Batman2814 Have you sent the system bug report as mentioned in [this comment](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/269#issuecomment-1597445200)? 
We see a bunch of logs from VPN application, but system bug report seems to be missing.

**Comment by Batman2814** [comment]
Got an email from AdGuard saying that you got the logs and above your saying that the system bug report seems to be missing. Can you clarify the accurate information?

**Comment by Versty** [comment]
@Batman2814 Yes, we see a lot of logs exported from the AdGuard VPN application, but no such files as logcat log or system bug report, which have been requested in https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/269#issuecomment-1597445200

**Comment by Versty** [comment]
@Batman2814 Hi! 
Have you sent the system bug report from your device? 
The cause may be inside the system, so it is important to examine the system interactions of your device.

**Comment by Versty** [comment]
@Batman2814 Closed due to inactivity. 
Please reopen if you find an opportunity to send system logs from your device.
