### ISSUE TITLE
After installing App on Android TV, unable to use Chromecast

### ISSUE THREAD

**Issue by alextallinn** [AdguardTeam/AdGuardVPNForAndroid#274]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

The las one from Playmarket

### Operating mode

None

### Environment

```markdown
- OS:Android TV ~10 Sony
- Device:Sony TV
- Firmware:
Impossible to configure local LAN excluded from VPN, like on Windows base client, my network 192.168.1.0, default Windows based client use only 192.168.0.0, but it is possible to add another mask.
No configuration page.
Do not keep connection all the time.
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Start programm, make VPN connection
2. Try to start something from other device using Chromecast. Device is visible, but impossible to execute.
3. Disconnect VPN -> Chromecast working fine.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@alextallinn I have tested this on the chromecast and I have not had this problem repeated. I have connected with three different devices with no problem and am running the chromecast.
Please describe, step by step, what you are doing to reproduce the problem.
What device are you trying to connect to the chromecast? What OS does the device have? What version of firmware does your chromecast have?

**Comment by alextallinn** [comment]
I will check versions after, but I think this is not related with versions.
As I sow in default configuration on Android Mobile, I see you are using IPv4 exclude mask:
192.168.0.0/16
But if I have another network mask: 192.168.1.0/16 it is not working. Why don't you take it dynamically after registered in DHCP and IP is already known?
Default masks should be accepted, Most router uses 192.168.0.1 and 192.168.1.1.
Also Android TV version do not have any configurations, it it possible to enable it? Normally it is not used its true, but it is possible to attach keyboard/mouse to it or use default onscreen keyboard to enter data.
For example AdGuard add blocker has a working UI on Android TV, but it is not visible in application list and this is sad.
And really I was surprised when YouTube Adds was decreased(it present in start and end but was disabled in the middle of video) and I do not know who blocks it AdGuard AddBlocker or AdGuard VPN (both of them installed and configured).

**Comment by maxikuzmin** [comment]
@alextallinn these masks actually give out the same number of addresses: 65536. They are the same.
Could you describe in more detail what you are proposing?
How often do you fail to connect from another device to your TV using Chromecast? 
Our version of AdGuard VPN for Android will be finalized in the future, for now there is no possibility of advanced settings.
You didn't mention the YouTube problem before, could you describe it in more detail?
Globally, we are aware of the complexities of Chromecast and VPN interaction, we will prepare an article on our FAQ about it a little later.

**Comment by maxikuzmin** [comment]
@alextallinn we published an article about Chromecast compatibility. It describes the problem with VPN and Chromecast interoperability, you can learn more about that [here](https://adguard-vpn.net/kb/ru/adguard-vpn-for-android/solving-problems/chromecast/).
For the moment, I'm closing this issue
