### ISSUE TITLE
An UI for Exclude Apps (plus Include Mode)

### ISSUE THREAD

**Issue by alexgieg** [AdguardTeam/AdGuardVPNForAndroid#277]
### Issue Details

My core VPN use is to get messaging apps that now and then get blocked by my country to work during those blocks. Other than that I don't need the VPN to be active, and in fact would prefer it not to be, because applications meant to be run within the country sometimes behave oddly when accessed from outside it. Besides, having a VPN on for everything might be seen as suspicious as my country slowly moves into more and more censorship: what is that person hiding that they only connect with these IPs abroad and nothing here?

My current workaround is to set AdGuard VPN for a US server, manually tap the Connect link on the Notifications area whenever I want to check new messages on a messenger, then tap on Disconnect to resume normal use.

Note: I also use AdGuard with AdGuard VPN, so it redirects me to AdGuard's app management to configure tunneling, but I don't see any option there that doesn't involve simultaneously disabling AdGuard and AdGuard VPN for an app. I'd like to only disable the VPN, not the ad-blocking.

### Proposed solution

The most immediate solution would be a proper UI for the exclude apps window (Settings -> App settings -> Advanced settings -> Low-level settings -> Excluded apps) allowing users to see a list of all apps, then tap on those they want do exclude from being VPNed. This would preserve the functionality without changing much about it other than being more convenient than figuring out app IDs elsewhere to then type them in a text list.

### Alternative solution

A better option would be, in addition to the above screen, a switch allowing AgGuard VPN to work in include mode. This way, instead of a long sequence of tap, tap, tap, tap... to exclude apps from the VPN, I'd be able to tap on those few I do want to have redirected through the VPN, with everything else not-VPNed.

PS: Sorry if this is a duplicate suggestion. I searched the issues but didn't find a similar suggestion. Maybe it's there but I didn't type the proper terms to find it.

**Comment by Versty** [comment]
@alexgieg Hi! 
If both apps are running in the Integration with each other, you can manage the tunnelling for the apps on the `Apps operating through proxy` screen. *AdGuard -> Filtering -> Apps -> Apps operating through proxy*

The app will be routed via AdGuard and won't be routed through AdGuard VPN, if you disable the switch for this app on the `Apps operating through proxy` screen.

**Comment by alexgieg** [comment]
@Versty I cannot find this screen. When I open _AdGuard -> Settings_, there's no _Filtering_ entry. There's a _DNS Filtering_ one, but within it there's no _Apps_ option. I looked around the other options but couldn't find an "Apps operating through proxy" in them either.

PS: I'm running AdGuard for Android v3.6.11 (54). Is this perhaps a new option in the v4 beta?

**Comment by mahara** [comment]
@alexgieg I think she meant _AdGuard -> **Apps Management** -> App (App Name) -> AdGuard protection (Route app traffic through AdGuard)_.

**Comment by mahara** [comment]
> @alexgieg Hi! If both apps are running in the Integration with each other, you can manage the tunnelling for the apps on the `Apps operating through proxy` screen. _AdGuard -> Settings tab -> Filtering -> Apps -> Apps operating through proxy_
> 
> The app will be routed via AdGuard and won't be routed through AdGuard VPN, if you disable the switch for this app on the `Apps operating through proxy` screen.

@Versty As of AdGuard 3.6.11, that doesn't seem to work that way. It would completely disable **BOTH** AdGuard and AdGuard VPN. You can see as well that the _Ad blocking_ option would be disabled (grayed out) as soon as _AdGuard protection_ disabled.

**Comment by mahara** [comment]
@Versty Did you mean the _**Selective app proxying**_ in https://adguard.com/en/blog/adguard-v4-0-for-android-nightly.html?

But it's not available in 3.6.x, right?
