### ISSUE TITLE
White screen on launch after revoking any permission for the app in the system settings 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdGuardVPNForAndroid#283]
### Version
AdGuard VPN 2.3 nightly 14

### Environment
Android 13, SCG09 

#### Prerequisites 
Notifications are allowed for AdGuard VPN in the system settings 
#### Steps 
1. Launch AdGuard VPN 
2. Open the system setting and revoke the notification permission for AdGuard VPN (Settings-> Apps -> AdGuard VPN -> Notifications)
3. Return to AdGuard VPN application 

### Expected behaviour 
AdGuard VPN is successfully opened

### Actual behaviour
AdGuard VPN is stuck on the white screen for 15 seconds, then opens

**Comment by artemiv4nov** [comment]
It's normal behavior. Application has relaunched after you revoke permissions. During launching we also update the sensitive app information. On specific networks this may take a bit more time.
