### ISSUE TITLE
Getting error code E010017 with the bing app on Phone

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#288]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Version 2.3 Nightly 18

### Operating mode

None

### Environment

```markdown
- OS: Android
- Device:Samsung
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. download the Bing app on a smartphone (Integrated with Chat GPT)
2. turn on Adgaurd VPN 
3. open App by pressing b to bring up the chat

### Expected Behavior

should work no matter what region I'm in.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

When I got that error code I had it on the United States Atlanta Server where it gave me that message saying not supported in your region. So I switched it up to New York where I could open the Chat GPT in the Bing app. So I looked it up and it told me it could be a problem with your VPN Provider because it said bing should have no issues working in the United states on the servers.

**Comment by Batman2814** [comment]
![Screenshot_20230525_194101_Bing](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96619913/9d287769-d442-427f-a99e-be59eb1863ee)

**Comment by Versty** [comment]
@Batman2814 Hi! Thank you for the details provided. 
If you open ChatGPT directly from any browser using Atlanta server, would it work then?

**Comment by Batman2814** [comment]
No, it won't work if I open Chat GPT from any other browser. When I do open Chat GPT from the actual website, the only way that I can use it with the Adguard VPN is to put "chat.openai.com" in the exclusions list in AdGuard VPN. When using the Bing app on Android, which is integrated with Chat GPT, I get that message. But also, when I have it on the New York server, it does seem to work but just takes time to load. On the Atlanta server that when I get that message. There could be other servers to by way.

**Comment by Versty** [comment]
@Batman2814 Got it, this issue is known and related to the IP of Atlanta server. Reproduces on our side as well. 
As a temporary solution, please use other locations in AdGuard VPN.

**Comment by Batman2814** [comment]
Do you know if this issue has been fixed on Atlanta Server? Do you think I can use the server without any problems now?

**Comment by Versty** [comment]
@Batman2814 Not yet, please temporary use other servers to gain access to ChatGPT or the Bing AI assistant.
