### ISSUE TITLE
Logger endlessly creates a new log file

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForAndroid#290]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

most recent release version

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS: 12
- Device: manufacturer=Wingtech model=TMAF035G brand=T-Mobile version=12 
- Firmware: n/a
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.  Launch AG and AG VPN in the compatibility mode
2. Observe the issue

### Expected Behavior

AG VPN does not crash and is fully operable (you are able to navigate through the UI)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

> However when I open the Adguard VPN app I can't access any menus or change my location because the buttons in the user interface will not work at all when I press them. So I cannot go Into settings or change my location.
> 
> I have reset the cache, delete data, update app, reset phone... In every combination and the app is still crashing right after it gets opened, every single time 

CRM ID: 703805, 761522, also, there's a discussion thread in the internal triague queue

**Comment by maxikuzmin** [comment]
@Eugene-Savenko we will definitely look into this in the near future.
