### ISSUE TITLE
VPN crashes upon startup on TMobile revvl 6 pro 5g

### ISSUE THREAD

**Issue by CrappyPhoneUser420** [AdguardTeam/AdGuardVPNForAndroid#295]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Newest

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 12
- Device: revvl 6 pro 5g
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open app
2. App crashes
3. Repeat

### Expected Behavior

App works fine like it does on my other phone and computer

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I have gone through emails with support and they sent me here I paid for 5 years of this service and it works on every device but this one.

**Comment by maxikuzmin** [comment]
@CrappyPhoneUser420 thanks for the long wait. 
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Open AdGuard VPN app settings;
- Advanced settings --> Logging level --> Extended;
- Reproduce the issue and remember the exact time it happened;
- Open Support --> Export logs and system info;
- Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by maxikuzmin** [comment]
@CrappyPhoneUser420 any news?

**Comment by maxikuzmin** [comment]
@CrappyPhoneUser420 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
