### ISSUE TITLE
Adguard Vpn AndroidTV - No option to login with external account

### ISSUE THREAD

**Issue by therockguy12** [AdguardTeam/AdGuardVPNForAndroid#298]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.2

### Operating mode

VPN

### Environment

```markdown
- OS:AndroidTv
- Device:Nvidia Shield
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Open App
2. No option to login with external account (eg, Google, apple)

### Expected Behavior

Options should be available to access the app with external accounts as available on other platforms.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@therockguy12 thanks for your feedback! The AdGuard VPN for Android TV app has little functionality right now, you're right. In the future, we will definitely add this feature as well as many others like AdGuard VPN for Android for mobile. Please wait a little longer.
Now we are collecting the main wishes on AdGuard VPN for Android TV [here](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/304), where users can give likes, and features with a large number of likes we will consider first.
You can also write other wishes directly in [this](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/304) issue.
I'm closing this issue.
