### ISSUE TITLE
Add more functionality for Android TV version

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdGuardVPNForAndroid#304]
### Issue Details

We currently have an AdGuard VPN for Android product that is compatible with Android TV.
AdGuard VPN for Android TV is quite fresh and has basic functionality. In the future we plan to improve AdGuard VPN for Android TV functionality similar to the mobile version, gradually we will add all the necessary features.
At the moment, we are collecting feedback from users to understand what should be added to AdGuard VPN for Android TV first.
Please post what you are missing first. We'll keep track of that, and we'll also track your likes under each post to understand the highest priority features

**Comment by maxikuzmin** [comment]
Add the ability to log in to your account using Google, Facebook, Apple 
https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/298

**Comment by githubuser013** [comment]
Please add custom DNS server like adguard for android or the VPN, so we can use our adguard private DNS.

**Comment by rakleed** [comment]
Login using a PIN code, which must be entered on another device where you have previously logged into your AdGuard account. Because if the password is very long, it can take several minutes to enter it, which is very inconvenient: #362

**Comment by funthomaspr1** [comment]
Android tv unfortunately all use Adguard vpn.  It is very bad that you have to turn the vpn on and off.  Because there are things that do not require the use of a VPN.  When can you expect to be able to choose which vpn tunnel to use on Android TV or Google TV?  For example, on an Android phone, you can choose which apps do not use Adguard vpn.
