### ISSUE TITLE
When AdGuard VPN is on Wyze Camera App, it says problem connecting with server.

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#307]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Version 2.3.1

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS: Galaxy Phone
- Device:Samsung 
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.turn on adguard VPN 
2. Then open wyze camera app if you have a wyze camera setup in app
3.

### Expected Behavior

Should not show at all. The server should work when VPN is connected.

### Screenshots

![Screenshot_20230709_142545_Wyze](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96619913/75eaf788-a38f-49a2-b673-69442ba6dce0)

### Additional Information

I'm using Private AdGuard DNS setup in AdGuard Adblocker. I made sure that it was the AdGuard VPN by turning off the VPN and just have AdGuard enabled and using the Wyze Cam App where it showing it was working without that message being displayed. I even changed the DNS in AdGuard by using Regular AdGuard DNS and Google DNS, and it showed that everything was working.  The only problem was when enabling AdGuard VPN.

**Comment by Batman2814** [comment]
Logs have been sent.

**Comment by Versty** [comment]
@Batman2814 Hi! 
If the problem occurs in the integrated mode only, please disable the `Route app through proxy` switch for the Wyze Camera applications in the AdGuard.

**Comment by Versty** [comment]
@Batman2814 Does the solution above help?

**Comment by Batman2814** [comment]
It does help when "route app through proxy" is disabled where I don't get those errors. But when I was testing it when proxy was turned on at times, it does seem to work without those errors, so my guess it is not some kind of bug that can be fixed to make it more stable.

**Comment by Versty** [comment]
@Batman2814 Yep, this behaviour highly depend on a third-party app, Waze Camera app in this case.

**Comment by Batman2814** [comment]
So would the best thing I can do is to try to get a hold of the Wyze Camera App support to let them know about the issue to see if they can fix the issue on there side to be more compatible with AdGuard VPN for Android?
