### ISSUE TITLE
Enabled AdGuard VPN stops connection to Internet 

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#320]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Version 2.4 for Android 

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 13
- Device: Samsung 
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. When connecting Adguard VPN, the connection becomes blocked, so I have to keep disconnecting and connecting VPN for it to be refreshed 
2.
3.

### Expected Behavior

The connection should automatically work when connected so I don't have to keep refreshing the connection by disconnecting and connecting them to the VPN server.

**Comment by maxikuzmin** [comment]
@Batman2814 спасибо за долгое ожидание. К какому DNS серверу ты подключен? Ты пробовал это без DNS? У тебя настроен Kill switch? Это происходит регулярно?

**Comment by Batman2814** [comment]
I'm connected to AdGuard Private DNS using the protocol QUIC. It does happen on a regular basis where I have to disconnect the VPN location I'm connected to and then reconnect it to a VPN location. Sometimes, I have to re-sync AdGuard before turning on AdGuard VPN for Android.

**Comment by maxikuzmin** [comment]
@Batman2814 it happens again without DNS? 
It'd be nice to see your logs.
Here's what we need you to do:

- Open AdGuard VPN app settings;
- Advanced settings --> Logging level --> Extended;
- Reproduce the issue and remember the exact time it happened;
- Open Support --> Export logs and system info;
- Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by Batman2814** [comment]
OK, sounds good.  Will do next time it happens.

**Comment by Batman2814** [comment]
Logs have been sent.

**Comment by Batman2814** [comment]
Logs were reproduced at 6:30 pm - 6:32 pm. Forgot to mention it in email when sending logs.

**Comment by maxikuzmin** [comment]
@Batman2814 thank you! We will check it.
Please check if you have Kill switch enabled, and try it again without DNS, or with a different DNS server

**Comment by Batman2814** [comment]
Kill Switch is N/A. I have AdGuard VPN for Android. Integrated with AdGuard Adblocker for Android, DNS is controlled from AdGuard Adblocker for Android.

**Comment by maxikuzmin** [comment]
@Batman2814 I see. Please wait, it will take us some time to figure out your problem
Check this also on the latest version 2.5.5 please

**Comment by maxikuzmin** [comment]
@Batman2814 any news?  Since the problem is happening in integration mode, could you repeat the problem again and get debug logs from both applications -  AdGuard and AdGuard VPN?

**Comment by Batman2814** [comment]
Ok, I'll send the logs once it happens again.

**Comment by maxikuzmin** [comment]
@Batman2814 any news?

**Comment by Batman2814** [comment]
I haven't caught the issue since I'm on the newer version of AdGuard VPN for Android. For now, I'll close the case and reopen it if I see the problem again.
