### ISSUE TITLE
Add Turkish Lira currency for AdGuard VPN website

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForAndroid#322]
### Issue Details

I've been a translator for Turkish at AdGuard for years, and users say it's too expensive for AdGuard VPN (for Turkey). You can see users' comments on Google Play. When I compare the AdGuard Ad Blocker with the Euro and the Turkish Lira, the Turkish Lira is 7 or 8 multiples of the Euro price.

### Proposed solution

Can you do the same for the AdGuard VPN (Turkish Lira currency) as in the AdGuard Ad Blocker?

### Alternative solution

Maybe you can do 9 or 10 multiples of the price for Turkish Lira.

**Comment by Versty** [comment]
@gork7777 We deeply appreciate your interest and willingness to translate AdGuard applications to Turkish. 

We also provide our most active contributors with licenses. So please contact translate@adguard.com if you need some assistance. 
Read more about the reward system in [this article](https://adguard.com/kb/miscellaneous/contribute/translate/rewards/). 

Speaking of Turkish Lira, we currently have no plans to add a regional price for this currency.
