### ISSUE TITLE
Polish news sites block AdGuard VPN

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/AdGuardVPNForAndroid#323]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

v2.4 (14)

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS: Android 12
- Device: Xiaomi Mi 10T lite
- Firmware: MIUI 13.0.8
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Connect to VPN in AdGuardVPN app with Polish (Warsaw) server - not sure if servers from other countries will cause the same problem
2. Open (preferably in incognito mode in browser):
a) rmf24.pl - the page is not loading or the images are not loading
b) or interia.pl and try to  open any news on that page - will not load

### Expected Behavior

I want the pages to open properly

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/77172951/6efffd1d-00ac-4eec-ac9d-3b3b195033ee)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/77172951/17681c7f-b2fd-4f73-b1f0-628927dc2c81)

</details>

**Comment by ESurina** [comment]
Thank you for letting us know about this issue. We will fix it as soon as possible! For now, you can use other servers to access these sites.
