### ISSUE TITLE
Auto-connect to adguard VPN when opening Instagram

### ISSUE THREAD

**Issue by RyJeRT** [AdguardTeam/AdGuardVPNForAndroid#324]
### Issue Details

Auto-connect to adguard VPN when opening Instagram

**Comment by Versty** [comment]
@RyJeRT The feature you are requesting has been discussed with the developers. Currently we have no plans to implement this option. 

However, we already have convenient ways to manage connection state - Tile for the Quick Access panel and shortcuts. 
Additionally, if you're looking for ways to automate this case, IFTTT is the best choice.
