### ISSUE TITLE
AdGuard VPN can't connect to location when using WIFI 

### ISSUE THREAD

**Issue by Nemisor** [AdguardTeam/AdGuardVPNForAndroid#330]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.3

### Operating mode

VPN

### Environment

```markdown
- OS: Android 14 UPB5.230623.006
- Device: Pixel 7
- Firmware:MP1.0
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Establish connection (this can be over wifi or cellular, doesn't matter)
2. Start Speedtest or Twitch stream
3. Test will begin but will randomly claim connection error, not always at the same point or during upload or download tests.
4. Connection silently breaks in the background and then resumes, some notifications or pages may not load, then suddenly they will load again.

### Expected Behavior

Expect connection to remain stable during streaming data or queuing uploads/messages.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I have two identical Pixel 7's (work and personal) and the issue started approximately a week ago on both of them. Reverted to stable build and verified the issue is unique to beta. It will silently break connection or fail to lookup DNS at random. It also fails to connect at work when it formerly worked, but only the beta app. I can supply logs if needed.

**Comment by maxikuzmin** [comment]
@Nemisor to troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Open AdGuard VPN app settings;
- Advanced settings --> Logging level --> Extended;
- Reproduce the issue and remember the exact time it happened;
- Open Support --> Export logs and system info;
- Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by maxikuzmin** [comment]
@Nemisor could you also attach a video of the screen with the problem so we can better understand the gist. I haven't been able to reproduce this yet

**Comment by Nemisor** [comment]
Logs from both phones sent to the devteam@adguard.com address, I will include a video if we can get it working on wifi next.

**Comment by Nemisor** [comment]
I believe the silent connection failure issues have been resolved in the latest betas (still updating the app on my personal cell) but the inability to connect to wifi at work is still an issue.

For more context, I can still connect to the same wifi using a chromebook with the adguard VPN extension (DNS over TLS) but the phone using adguard beta (DNS over QUIC) does not connect, and yes I have tested all methods of DNS including TLS and unencrypted on the phone and they have no impact.

**Comment by Nemisor** [comment]
It just sits at the Connecting screen and never changes. No error message until it eventually claims the server isn't responding.

**Comment by Nemisor** [comment]
Latest beta 2.5.12 resolves this issue, thanks guys!
