### ISSUE TITLE
Adguard VPN for android tv is not starting 

### ISSUE THREAD

**Issue by ywanpot** [AdguardTeam/AdGuardVPNForAndroid#331]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.5

### Operating mode

VPN

### Environment

```markdown
- OS:Android tv
- Device:Sony kd-49h8596
- Firmware: 4.9.125
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. I stopped once ad guard
2. I tried to open ad guard, nothing happened 
3.I tried ro reboot, reinstall same results 

### Expected Behavior

Ad guard starts and show user interface 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment]
@ywanpot thank you! We are already aware of this and are trying to solve it.
As far as we know, this problem is recurring on the MI Box and Sony TV.
What kind of device do you have?

**Comment by ywanpot** [comment]
Hi! 
I've got Sony TV. It started after last firmware update.

**Comment by maxikuzmin** [comment]
@ywanpot please update to version 2.5.1, we fixed this issue!
