### ISSUE TITLE
Website freezes if added to Selective mode

### ISSUE THREAD

**Issue by Koruy** [AdguardTeam/AdGuardVPNForAndroid#339]
Не загружается (зависает) страница если в поисковике что то написать, например "форум adguard". П. С. Работает в связке с adguard vpn
![Screenshot_20230904_160412](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/53151866/b3ea88aa-4f90-4ae2-a6ad-850aeb4ca461)
![Screenshot_20230904_160335](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/53151866/d2fea6fd-5494-40b0-8f57-69ebc49b54e9)

**Comment by Koruy** [comment]
Дело в том у меня в настройках vpn работает только в определённых сайтах. В поисковике я могу написать любой запрос, который не фильтрует vpn, просто страница зависает. Решение отключить полностью adguard vpn. Тогда и с поисковиком проблем нет

**Comment by Koruy** [comment]
Без использования adguard vpn зависаний страниц нет несколько дней использования

**Comment by maxikuzmin** [comment]
@Koruy спасибо за долгое ожидание!
Т.е. ты используешь AdGuard VPN в выборочном режиме? Не мог бы ты экспортировать исключения и прислать их на почту devteam@adguard.com, чтобы я смог проверить это?

**Comment by maxikuzmin** [comment]
@Koruy на данный момент я закрываю этот вопрос. Если проблема снова повторится, пожалуйста переоткрой это
