### ISSUE TITLE
Improve name of file with exported list of exclusion sites

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForAndroid#340]
### Issue Details

Currently, when exporting a list of exception sites, the file is called `adguard_vpn_exclusions_0309_223432`, but I would like it to have a descriptive and uniform name on any device.

### Proposed solution

Name the file with the exported list of exclusion sites like this: `adguard-vpn_android_website-exclusions_2023-09-04_22-41-27`.

**Comment by artemiv4nov** [comment]
Well, it's interesting idea, let's call it "adguard_vpn_website_exclusions_0309_223432"
