### ISSUE TITLE
In `README`, logo is hard to see when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForAndroid#341]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

N/A

### Operating mode

None

### Environment

```markdown
- OS: N/A
- Device: N/A
- Firmware: N/A
```

### Root access

- [ ] Yes, I have it.

### Issue Details

In the https://github.com/AdguardTeam/AdGuardVPNForAndroid/blob/master/README.md, the logo is hard to see when using the dark theme on GitHub.

### Expected Behavior

You need to add a logo option for the dark theme. I wanted to do it myself by taking [this dark theme logo](https://github.com/AdguardTeam/AdGuardVPNExtension/blob/63d72c1dace95f4a332e2c350ad6b7ddf027a93d/src/assets/images/logo-vpn-dark.svg), but it doesn't have mentions to which platform the repository belongs, which is in the current logo.

Useful link: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/19418601/fdb9bbe1-2cfc-47e0-88bf-dd568ea58103)

</details>

**Comment by Versty** [comment]
@rakleed Fixed
