### ISSUE TITLE
Connection doesn't work when using only IPv6 as preferred IP version

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForAndroid#342]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

v2.5 (5)

### Operating mode

VPN

### Environment

```markdown
- OS: Android 14
- Device: Pixel 3A
- Firmware: N/A
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Go to AdGuard VPN settings
2. Go to App settings
3. Go to Advanced settings
4. Go to Low-level settings
5. Click on Preferred IP version and choose IPv6
6. Try to connect to any server

[adguard_vpn_logs_2.5.5_0509_040515.zip](https://github.com/AdguardTeam/AdGuardVPNForAndroid/files/12517809/adguard_vpn_logs_2.5.5_0509_040515.zip)

### Expected Behavior

The connection works correctly when using only IPv6 as the preferred IP version.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_1693875908](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/19418601/3b43c6cd-fb3a-4695-a605-4da2a692e89a)

</details>

**Comment by Versty** [comment]
@rakleed Hi! 
Does your network support IPv6? Please also check if the `Enable IPv6` toggle switch is enabled in the low-level settings.

**Comment by rakleed** [comment]
@Versty should it be supported? I thought that even if it doesn’t support it, then when I connect to AdGuard VPN I will have an IPv6 address.

**Comment by Versty** [comment]
@rakleed Sure, IPv6 should be supported by your network to work properly. 
Has this case been resolved?

**Comment by rakleed** [comment]
can you add information about this to https://adguard-vpn.com/kb/adguard-vpn-for-android/overview/#advanced-settings?

**Comment by Versty** [comment]
@rakleed Sure, will be added to the article.

**Comment by el-termikael** [comment]
https://github.com/AdguardTeam/KnowledgeBaseVPN/pull/184
