### ISSUE TITLE
Не могу отправить отчёт

### ISSUE THREAD

**Issue by Koruy** [AdguardTeam/AdGuardVPNForAndroid#346]
Не могу отправить отчёт
![Screenshot_20230908_105504](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/53151866/03a7c0d2-30c0-4615-8a17-6a729d5488e8)

**Comment by ESurina** [comment]
Здравствуйте, уточните, пожалуйста, как часто появляется данная ошибка, какая версия приложения у вас установлена и какая версия андроида стоит на вашем устройстве?
Попробуйте установить последнюю версию AdGuard VPN (2.5.3) и отпишитесь, пожалуйста, будет ли снова возникать такая ошибка.

**Comment by Koruy** [comment]
Сейчас отчёт об ошибке отправился
![Screenshot_20230920_211834](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/53151866/40199559-59ff-4709-b20c-ea35460019a3)
Версия андроид 13. Версия adguard vpn 2.5.3

**Comment by Koruy** [comment]
Теперь к сути ошибки. В режиме интеграции с adguard не грузятся страницы, пока не отключу приложение adguard vpn. Adguard vpn работает в данном режиме. На скриншотах указана не загрузка страницы и настройки приложения. 
![Screenshot_20230920_211910](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/53151866/b235ec32-a52e-4785-af93-a627d24a36d8)
![Screenshot_20230920_212336](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/53151866/73d9230c-e8e4-420d-ac93-20cb46286d4e)

**Comment by ESurina** [comment]
При интеграционном режиме используется протокол IPSec, который сейчас имеет ограничения со стороны провайдеров. Мы делаем все возможное для поддержки доступности сервисов. На данный момент советуем использовать AdGuard VPN в режиме VPN.
