### ISSUE TITLE
Выкидывает из приложения

### ISSUE THREAD

**Issue by Koruy** [AdguardTeam/AdGuardVPNForAndroid#353]
Выкидывает из приложения, защита не запускается

**Comment by maxikuzmin** [comment]
@Koruy thanks спасибо за долгое ожидание. Не могли бы вы уточнить шаги для воспроизведения проблемы? Это всё ещё повторяется на версии 2.5.5?

**Comment by maxikuzmin** [comment]
@Koruy есть новости?

**Comment by maxikuzmin** [comment]
@Koruy на данный момент я закрываю этот вопрос. Если проблема снова повторится, пожалуйста переоткрой это
