### ISSUE TITLE
Notification shade icon is not Material You themed

### ISSUE THREAD

**Issue by TigerCraneStyle** [AdguardTeam/AdGuardVPNForAndroid#361]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

v2.5.3 (16)

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 13
- Device:Google Pixel Fold
- Firmware:TQ3C.230901.001.A1
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Make sure Adguard VPN is running. 
2. Swipe down for the notification shade. 
3. Here you'll see that the notification icon for Adguard VPN is not themed to Material You like the icon would be if it were on the homescreen. It's like this on the lock screen also. 

### Expected Behavior

The icon for Adguard VPN should be Material You themed in the notification shade and lock screen just like it is for Adguard Adblocker. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

As you can see from the screenshots, the Adguard VPN icon should be the same color as the Adguard Adblocker icon in the notification shade and lock screen. 

![Screenshot_20230921-174526](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/131628729/ee99e08b-9be4-4a3e-b71f-65ee7b2055b1)
![Screenshot_20230921-173223](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/131628729/069d8d6b-82e0-4390-ab7c-bc36779446ce)

**Comment by ESurina** [comment]
Thank you for bringing this issue to our attention. We will fix it in the next versions!
