### ISSUE TITLE
Limited

### ISSUE THREAD

**Issue by JosephL5866** [AdguardTeam/AdGuardVPNForAndroid#363]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Free version

### Operating mode

None

### Environment

```markdown
- OS:android
- Device: REVVL 6 Pro phone
- Firmware:up to date
My VPn is supposed to be beta I have downloaded from your beta site it is free version I cannot access all features does not let me connect to all servers same as the version I downloaded from Google play I jptbah@gmail.com. beta tester limited access have not recieved any beta update so my feed back will be linited and not completely accurate .I was told that I coujd keeo the beta vwrsion from your site ro test i have nit recieved any beta version. So my assessment will not be a 5 star rating it will only be on what I had access to which was limited I have to give t

These apps back I cannot test the free version it doesn't perform the way a purchased or beta version would I was hoping to beta test but feedback on frr version . The VPN is limited wilk not let you connect to all the servers. Limits your connection time you have to earn gigabytes to stay connected. The app would perform better connected to Adguard as blocker  and adguard dns unfortunately I only have free version which are limited so at this time the free versions wikk work but there are better free options i hate to say that I find adguard products superior to other apps on class. Not the free version though the free versions definitely let you know how well the full versions will work just in the free category the do not out perform other free versions I will not name them if you would like those names. You have to email me. If you are purchasing a vpn adguard is a wonderful choice their ad locker out perform the nearest competitor that is our there that would be TotalAV. Adguard is far superior.
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.
To be given unrestricted app

### Expected Behavior

I expected beta version to have unlimited access to the apps 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

The app will not connect to all servers and does not recognize the other adguard products I downloaded to grant more gigs for the VPN. Still would love to beta test

**Comment by JosephL5866** [comment]
Adguard full version are a superior to other apps in there class every bit as good if not better in all aspects

**Comment by maxikuzmin** [comment]
@JosephL5866 thanks for your review! The beta version of AdGuard VPN has almost the same features as the release version. You need to have a paid subscription for full access to all locations. Could you be more specific about what exactly you want? 
If you want to become a beta tester, you can find out more about it [here](https://adguard-vpn.com/en/beta.html?platform=android&release=nightly).

**Comment by maxikuzmin** [comment]
@JosephL5866 if you have no more questions, I'm closing this issue.
