### ISSUE TITLE
Wi-Fi auto-protection doesn't work if you turn it on when wi-fi connection is disabled

### ISSUE THREAD

**Issue by ESurina** [AdguardTeam/AdGuardVPNForAndroid#375]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.5

### Operating mode

None

### Environment

```markdown
- OS: Android 12 + MIUI 13, Android 10 + Harmony OS 3
- Device: Xiaomi, Huawei
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Wi-Fi connection and VPN connection are disabled.
2. Go to Settings -> General -> Wi-Fi auto-protection.
3. Turn on Wi-Fi switch.
4. Turn on Wi-Fi connection.

VPN is not connecting.

### Expected Behavior

VPN is connecting.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

It also doesn't connect if you restart the app.

**Comment by artemiv4nov** [comment]
Auto protection has been terminated and no longer exists in application
