### ISSUE TITLE
Как скачать Vpn на Huawei

### ISSUE THREAD

**Issue by Kawasalto** [AdguardTeam/AdGuardVPNForAndroid#407]
### Issue Details

Как скачать ваше приложение, которое совместимо с harmony OS, если на huawei не работает playmarket а в appgallery приложение отсутствует???

**Comment by Eugene-Savenko** [comment]
Ну вот же: https://appgallery.huawei.com/#/app/C109518601

**Comment by Versty** [comment]
@Kawasalto Загрузите приложение в формате .apk с [нашего официального сайта](https://adguardvpn-help.com/ru/android/overview.html) и установите по инструкции, которая появится на экране при загрузке файла.
