### ISSUE TITLE
Integrated Mode Fallback

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardVPNForAndroid#410]
### Issue Details

Right now, when AGVPN is running in Integrated mode, it will completely disable VPN tunnelling whenever AG is disabled (e.g., #306 or whenever manually disabled for whatever reason).

### Proposed solution

It'd better for AGVPN (under _any_ platform) to fallback to direct VPN tunneling until AG is reactivated, especially since AGDNS is typically being used by it.

### Alternative solution

Leaving it as-is isn't particularly good, as it leaves the connection completely unarmored.

**Comment by sfionov** [comment]
@TPS Hmm, actually integrated mode works exactly how you described. When AG VPN is connected, and AG becomes off, AG VPN automatically sets VPN service up.

**Comment by TPS** [comment]
Yes, but what happens when AG becomes unloaded once AGVPN is active?

**Comment by Versty** [comment]
@TPS AdGuard VPN switches to VPN operating mode as a fallback for cases when AdGuard for Android application is not running. To use this feature you should have AdGuard VPN profile installed in the system settings. It is also important to make sure that any other VPN in the list have no `Always-on VPN` option enabled.

**Comment by TPS** [comment]
Ok, but when Always-On VPN is _required_ for system security, how is fallback to work?
