### ISSUE TITLE
Make the arrows and three dots increase in proportion to the font size

### ISSUE THREAD

**Issue by ESurina** [AdguardTeam/AdGuardVPNForAndroid#414]
### Issue Details

Now if you change a font size to a bigger one, arrows (back buttons) and 3 dots (context menu) are still small. People with poor eyesight will not see them.

### Proposed solution

It would be nice to make the arrows and dots change their size according to the font size.

**Comment by acediat** [comment]
We decided to leave it as is for now

**Comment by acediat** [comment]
We decided to leave it as is for now
