### ISSUE TITLE
The selected location resets to the default location after restarting the application 

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdGuardVPNForAndroid#425]
### Version
AdGuard VPN for Android 2.7.1 beta 1

### Environment
Android 13, SGC09

### Steps to reproduce 
1. Select "Norway, Oslo" location from the list
2. Disconnect and close AdGuard VPN completely 
3. Launch AdGuard VPN 

### Expected behaviour 
The "Norway, Oslo" location is selected and is displayed on the Home tab 

### Actual behaviour
The fastest location is selected and is displayed on the Home tab 

### Additional 
In the 2.7 release version, the location memorization worked as expected

**Comment by TPS** [comment]
https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/306#issuecomment-1902621917?
