### ISSUE TITLE
New servers in Brazil, the current one has high latency

### ISSUE THREAD

**Issue by zystemdanny** [AdguardTeam/AdGuardVPNForAndroid#431]
### Issue Details

Greetings Team Adguard. I have a complaint regarding the location of Brazil, where the current servers have high latency and should not be.
I am from Latin America and the latency of Argentina as well as Chile, they are quite stable, but not Brazil. I share two screenshots here so you have an idea of what I am talking about.

![Screenshot_20240305_101301_AdGuard VPN](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96546237/8b5873f8-4630-4135-83c6-dab514527a87)
![Screenshot_20240305_101318_AdGuard VPN](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96546237/8c1d2aad-bb94-469d-8197-591fe5b46e9e)

### Proposed solution

I recommend that you put servers of the **datapacket** company or **gcore** company, it will be of great help and will have less latency. Thanks for the help.

**Comment by ESurina** [comment]
Thanks for your feedback! The developers have considered the possibility of using servers from another company, but at the moment the decision has been made not to change the server.
