### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by mohammedthejihadist** [AdguardTeam/AdGuardVPNForAndroid#436]
### Issue Details

Your VPN is not on F-Droid

### Proposed solution

Your VPN seems pretty good you should put it on F-Droid, which is superior to Google Malware Store.

**Comment by TPS** [comment]
Effectively https://github.com/AdguardTeam/AdguardForAndroid/issues/1148

**Comment by ESurina** [comment]
We discussed your proposal and unfortunately came to the decision not to publish our application on F-Droid.

**Comment by TPS** [comment]
How about making closed-source repos, as requested in https://github.com/AdguardTeam/AdguardForAndroid/issues/1148#issuecomment-488702638?
