### ISSUE TITLE
AdGuard VPN concerns

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#443]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

I am experiencing difficulties in establishing a connection to the servers across all AdGuard VPN products. Can you please assist me in resolving this issue?

**Comment by PavelParkhomenko** [comment]
Hello there!
To better assist you, could you kindly provide additional details regarding your request? For instance, sharing a screenshot or providing a more detailed description of the issue you're facing would be helpful.
Could you also specify on which device the problem occurs and which app version is currently installed on this device? Additionally, have you tried restarting your device or reinstalling the app to see if that resolves the issue?
