### ISSUE TITLE
A UI Lag of the application

### ISSUE THREAD

**Issue by jenabaivab** [AdguardTeam/AdGuardVPNForAndroid#45]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [YES] I am running the latest version
- [YES ] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  1.0.259
- **VPN mode:** 
  - SOCKS5
- **Device:**
  - Realme X2
- **Operating system and version:**
  -  10
- **Root access:**
  -  No

### Expected Behavior

It should be running at a smooth pace without any lags in between.

### Actual Behavior

The app gets stuck a lot. I start the app and after a second or two none of my touches register. It hangs for a few seconds before it works normally again. Then again after 2 seconds it's stuck. I have been using since this since the first build of Adguard VPN and I have seen this issue since about a month or so.
I can barely connect any location considering it doesn't let me use the app properly and I can't even tweak any settings to find out what is causing the issue.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by artemiv4nov** [comment]
@jenabaivab hi!
Could you write the list of the exact steps, how to reproduce it, please?

**Comment by jenabaivab** [comment]
Hello!
It's actually the moment I launch the app. There is no extra set of steps that I have to reproduce. It's just unresponsive the moment I open it.
I'll show you with a video, please wait.

**Comment by jenabaivab** [comment]
@artemiv4nov 

https://streamja.com/EwLNn

Please have a look here. Note at the start of the video, I am showing how dragging from the bottom is my home gesture. 
After the app is opened, you can see all the touches at the bottom bar. You can see how many times I am trying to go home, or even switch tabs.

**Comment by Ruslanrem** [comment]
@jenabaivab Can you do these steps please:
1. Open AdGuard VPN settings;
2. Advanced settings -> Logging level -> Debug;
3. Reproduce the issue (and remember the exact time when it happened);
4. Export logs and system info (cogwheel button - advanced settings - export logs and system info) . Send the archive to `devteam@adguard.com` and mention this issue number in the subject.
And tell me please, where from you installed adguard VPN apk?

**Comment by jenabaivab** [comment]
@Ruslanrem as you can see in the above video, there is no specific step to recreate the issue. It just starts the moment I launch the app till I close it. I'll try and send the appropriate logs to the mail id mentioned.

This is the latest non-beta playstore build. I left the early access list last month thinking it was causing issues with the app. Tried again with the full release of the app, and got the same problem. That's why I thought it's best to report.

**Comment by Ruslanrem** [comment]
@jenabaivab Hi there, did you sent logs?

**Comment by jenabaivab** [comment]
@Ruslanrem the logs were sent on that day itself to devteam@adguard.com
![image](https://user-images.githubusercontent.com/60446763/100262017-97d41280-2f71-11eb-8f63-1c5b21f10ec5.png)

**Comment by ameshkov** [comment]
@artemiv4nov since we still cannot reproduce this, consider creating a test build that forces StrictMode with a very strict ThreadPolicy and "penaltyDeath" enabled. It will cause the app to crash and we'll receive a crash report with the threads state.

Also, according to the video, the problem is NOT caused by a UI thread blocking. In this case the rendering would've stopped completely and this is not the case (loader is still animated).

**Comment by lolka4toli** [comment]
There is common problem in the #1152540 helpdesk ID ticket. Video and logs with a more detailed info are included in a jira comment.

**Comment by dft601** [comment]
@artemiv4nov this is my ticket. Please tell me if you need more. But it is difficult to collect the data because of the issue with the UI.
Mike

**Comment by dft601** [comment]
Tell me what data you need. I thought I have sent enough logs weeks ago. But status is still waiting for data....

**Comment by artemiv4nov** [comment]
@dft601 Your case is quite complex because we can't reproduce the bug on usual devices.

But this task is scheduled by me and waiting in the queue. Please wait for the task status change.

**Comment by artemiv4nov** [comment]
@dft601 hi!
I already finished the bug research and almost finished the fix. I invite you to the private pre-alpha testing, where you could check whether the bug is fixed or not.
Please email me your Gmail account to devteam@adguard.com, and I'll send you an invite link.
