### ISSUE TITLE
AdGuard VPN fails to launch on Amazon Firestick 4K Max

### ISSUE THREAD

**Issue by BRiTiSHSM** [AdguardTeam/AdGuardVPNForAndroid#455]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.8

### Operating mode

VPN

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

Regular

### Environment

```markdown
- OS: FireOS 8
- Device: Amazon FireStick 4K Max
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. Install AdGuard VPN 2.8
2. Try to Launch AdGuard VPN
3.

### Expected Behavior

The app would launch

### Actual Behavior

The app opens the logon screen and then closes.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@BRiTiSHSM Thank you for reporting! 
Have you installed the application from Play Store or as .apk file? 
Does the previous version (2.7.1) of AdGuard VPN launch with no issues on your TV?

**Comment by Versty** [comment]
@BRiTiSHSM Any updates?

**Comment by Versty** [comment]
@BRiTiSHSM Closed due to inactivity, please reopen if needed.
