### ISSUE TITLE
Replace latitud.sh with datapacket in the country Argentina 

### ISSUE THREAD

**Issue by zystemdanny** [AdguardTeam/AdGuardVPNForAndroid#456]
### Issue Details

I have to admit that latitud.sh or its network does not work on certain websites when the VPN is activated. 

### Proposed solution

I ask the Adguard team to do the following: replace latitud.sh with datapacket.com in Argentina. New servers are in pre-order. 

### Alternative solution

If the above is not possible, I recommend the following provider for Argentina:

https://www.zenlayer.com/latin-america/

Thank you for listening to your users.

**Comment by D13410N3** [comment]
Can you provide more information?

**Comment by zystemdanny** [comment]
> Can you provide more information?

I will. When I use the Argentina server, certain web pages do not load nor does the Wild Rift (Android) game last time I checked. I have to switch from Argentina to Brazil or Chile for certain applications to work properly as well as web pages.
The basis of this replacement request is this reason I mentioned above and that datapacket could be better without problems.
In case datapacket can't do it, I ask to replace it with Zenlayer.

If you dare to investigate using the location of Argentina as for example: Wild Rift that can be downloaded at:

https://play.google.com/store/apps/details?id=com.riotgames.league.wildrift

You will see that it does not let you log in directly to your personal account, this is the same on other web sites. Latitude.sh is very fast to download, but I don't know why this happens if it is at the level of the server network or the server itself.

Thanks for the answer.

**Comment by zystemdanny** [comment]
@D13410N3 
> Can you provide more information?

I will. When I use the Argentina server, certain web pages do not load nor does the Wild Rift (Android) game last time I checked. I have to switch from Argentina to Brazil or Chile for certain applications to work properly as well as web pages.
The basis of this replacement request is this reason I mentioned above and that datapacket could be better without problems.
In case datapacket can't do it, I ask to replace it with Zenlayer.

If you dare to investigate using the location of Argentina as for example: Wild Rift that can be downloaded at:

https://play.google.com/store/apps/details?id=com.riotgames.league.wildrift

You will see that it does not let you log in directly to your personal account, this is the same on other web sites. Latitude.sh is very fast to download, but I don't know why this happens if it is at the level of the server network or the server itself.

Thanks for the answer.

**Comment by zystemdanny** [comment]
@D13410N3 
Here I share more information about the network issue using the Argentina server that won't let me log in completely to Wild Rift:

![Screenshot_20240524_161228_Wild Rift](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96546237/d9d33a38-d893-4320-b85a-bc6a6aed9f52)
![Screenshot_20240524_161205_Wild Rift](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96546237/2232f459-9477-478a-9c9b-4e5c29e2ee49)

I changed DNS and it doesn't solve the problem.

**Comment by D13410N3** [comment]
Maybe you should contact your game support with this question? I'm not sure if server replacement will help you in this case

**Comment by zystemdanny** [comment]
@D13410N3 
I don't think it is necessary. I'll tell you something, when searching for Android OS updates (Samsung with Android 13), it takes a long time to search and the other time I jumped error; if I use brazil or Chile for example, when searching for system updates it is fast. It doesn't only happen with that game, but with others and even websites that don't let me enter.

Try using Argentina and visit the following link to see if you get an error (try with any browser):
https://forobeta.com/

![Screenshot_20240527_134308_Firefox Nightly](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96546237/b3d09a2c-ac37-481c-8f10-be7531ce7667)


I'm attaching a sample image, if it turns out the same, we're on the same page. 

If you get an error, change to Chile or Brazil, if it lets you in, it's because of something and I don't know if it's the server or the network. I remember when I used NordVPN with the Argentina server which has exactly the same latitude.sh provider, there were some problems.

My advice is: replace the provider in Argentina.

**Comment by D13410N3** [comment]
It is still not a reason for a server replacement. Try another location or contact site owner with this question. There is a big chance that server replacement won't help. Also breaking some other site is a big chance too.
Latitude is a pretty good provider.

**Comment by zystemdanny** [comment]
> @D13410N3 
Greetings, the website ForoBeta used to work before, but now it's no longer functioning on the Argentina server. Can you fix it and also let me know what the issue is? Thank you.

Website not working since last time, for example:
1- http://browserleaks.com/
2- http://forobeta.com/
![Screenshot_20240714_162850_Firefox Nightly](https://github.com/user-attachments/assets/14e74a26-8942-437f-952c-42b5396cac3e)
