### ISSUE TITLE
TV: AdGuard VPN struggles to connect to location via ethernet cable

### ISSUE THREAD

**Issue by Aphexpusher** [AdguardTeam/AdGuardVPNForAndroid#457]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

V2.8.1

### Operating mode

VPN

### Which DNS server do you use?

Default

### DNS protocol

Regular

### Environment

```markdown
- OS: android 
- Device: Nvidia shield TV 2019
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1.when connecting to VPN it flickers between in and off in a loop.
2. Deleted app then reinstalled but no joy.
3.

### Actual Behavior

When turned on its flickering between on and off in a loop. I've deleted the app then reinstalled but the same issue.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

.

**Comment by Versty** [comment]
@Aphexpusher Thank you for reporting! 
Did you have this issue on the previous version of AdGuard VPN for Android (2.8 or 2.7.1)? 
Have you downloaded the app from Play Store?

**Comment by Aphexpusher** [comment]
Hi I've figured it out. When I'm connected via ethernet cable that's when
the problem occurs. I'm just using WiFi now. Thanks

**Comment by Versty** [comment]
@Aphexpusher Glad you have found the proper solution for your TV.
We have tried to reproduce the issue with ethernet cable, but to no avail.
