### ISSUE TITLE
Adguard VPN not working on Firestick [Adguard VPN 2.8+]

### ISSUE THREAD

**Issue by lukasb75** [AdguardTeam/AdGuardVPNForAndroid#460]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.8+

### Operating mode

VPN

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### Environment

```markdown
- OS: Fire OS (Android 10 or 11)
- Device: Amazon FireStick device
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. I downloaded the last app apk on Adguard VPN Website (AndroidTV page 2.8.2 version)
2.  I removed 2.7 version and installed 2.8.2 version
3. App crash every time during load screen

### Expected Behavior

The 2.7 version and before work fine.
No crash.

### Actual Behavior

 Crash every time during load screen.
 I tried 2.8 and 2.8.1 app version and is the same issue.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Could be a architecture problem (x86 / x64 / ARM) ?

**Comment by Versty** [comment]
@lukasb75, thank you for reporting! 

We are investigating this issue. Could you provide a bugreport from your device to help us find the cause? 
If so, please follow the steps below: 
1. Install [adb](https://developer.android.com/tools/releases/platform-tools#downloads) to your PC 
2. Unlock developer options and enable USB debugging on your TV as explained in [this article ](https://www.xda-developers.com/how-to-access-developer-options-amazon-fire-tv/)
3. Make sure that your TV and PC use the same network, and connect your TV to PC using the adb command
`adb connect xxx.xxx.xxx.xxx` where xxx.xxx.xxx.xxx is IP address of your TV 
4. Launch AdGuard VPN 2.8.3 and make sure that the app has crashed, note the time of this crash 
5. Use the `adb bugreport` command to collect bug report 
6. Send this file to devteam@adguard.com:
      - mention the `460` number in the subject
      - specify the exact time when the crash occurred

**Comment by lukasb75** [comment]
Ok it's done.
Hope it be helpful.

**Comment by Versty** [comment]
@lukasb75 thank you! 
We received the file.

**Comment by Versty** [comment]
@lukasb75 We have sent further instructions and .apk via email. Please try it and let me know results here or by email.

**Comment by Versty** [comment]
This issue was caused by installation of .apk file originally designed for mobile devices. 
The installation of the .apk for TV solved the problem.
