### ISSUE TITLE
Nextdns doesnt work

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdGuardVPNForAndroid#462]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.8.2 (223]

### Operating mode

VPN

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### Custom DNS

quic://9daf92.dns.nextdns.io

### Environment

```markdown
- OS: android 10
- Device: vseebox
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. Enter in custom dns 
2. Click save
3. Try using an app and there will be no internet

### Expected Behavior

That the custom dns resolves and is connected to the internet 

### Actual Behavior

Not connected to the internet.  Cant use my custom dns

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@jordanswrld94 We have tried to reproduce this issue, but to no avail. Therefore, we would like to take a look at the bug report from your device. 

Please follow the steps below: 
1. Upgrade AdGuard VPN for Android TV to the latest version (2.8.3)
2. Install [adb](https://developer.android.com/tools/releases/platform-tools#downloads) to your PC 
3. Unlock developer options and enable USB debugging on your TV as explained in [this article ](https://www.xda-developers.com/how-to-access-developer-options-amazon-fire-tv/)
4. Make sure that your TV and PC use the same network, and connect your TV to PC using the adb command
`adb connect xxx.xxx.xxx.xxx` where xxx.xxx.xxx.xxx is IP address of your TV 
5. Launch AdGuard VPN and reproduce the issue, note the time of reproduction
5. Use the `adb bugreport` command to collect bug report 
6. Send this file to devteam@adguard.com:
      - mention the `462` number in the subject
      - specify the exact time when the issue occurred

**Comment by jordanswrld94** [comment]
Im sorry i dont have a pc right now :(

**Comment by ameshkov** [comment]
I wonder could it be rate limiting? I.e. nextdns might be rate limiting DNS queries from a certain VPN server of ours (too many customers there are using nextdns for instance).

**Comment by jordanswrld94** [comment]
> I wonder could it be rate limiting? I.e. nextdns might be rate limiting DNS queries from a certain VPN server of ours (too many customers there are using nextdns for instance).

I think you're on to something.  I noticed that nextdns is faster when i dont use adguard vpn on my phone. Switched to cloudflare with vpn and huge difference i see.

**Comment by Versty** [comment]
@jordanswrld94, can we assume that the problem is solved for you?

**Comment by jordanswrld94** [comment]
Yes. Seeing as it is probably nextdns limiting data and not fixable on adguard side
