### ISSUE TITLE
Vpn is disconnected when i wake up

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdGuardVPNForAndroid#463]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.8.2 (223]

### Operating mode

Integration with AdGuard

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### Custom DNS

quic://9daf92.dns.nextdns.io

### Environment

```markdown
- OS: android 14
- Device: s23 ultra
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. Enable vpn
2. Leave it overnight 
3.  In morning its disconnected 

### Expected Behavior

For it to reconnect

### Actual Behavior

Was disconnected when i woke up

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by jordanswrld94** [comment]
Also i cant enable watchdog for adguard vpn 

![Screenshot_20240612_130449_AdGuard VPN](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/118186787/7f819036-6daf-454b-a393-71c1085f230e)

**Comment by tengizmax** [comment]
Hi there, @jordanswrld94 !
It seems like a bug. Please, give us the hand for deep investigation of your problem - send us an extended logs after you reproduce issue again.
For log export, please procedure next steps:

1) Enable debug logging:
Settings -> General -> Advanced settings -> Logging level -> Extreme
2) Reproduce the issue and remember the exact time when it happened
3) Collect logs:  Settings -> General -> Advanced settings -> Export logs and system info
4) Send this file to [devteam@adguard.com](mailto:devteam@adguard.com): 
- mention the #463 number in the subject
- specify the exact time when the issue occurred

Also tell more about battery usage and it permissions for AdGuard VPN app. 
Let be in touch, thanks.
