### ISSUE TITLE
VPN killed in integration mode 

### ISSUE THREAD

**Issue by ArrayKamko** [AdguardTeam/AdGuardVPNForAndroid#465]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.9 nighly 9

### Operating mode

Integration with AdGuard

### Which DNS server do you use?

Default

### DNS protocol

DNS-over-HTTPS

### Custom DNS

adguard-dns.io

### Environment

```markdown
- OS: Android 14
- Device: Vivo Y55 5G
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1.Use AdguardVPN and Adguard in Integrated mode
2. battery optimization is disabled for both apps
3.

### Expected Behavior

Do not disconnect or close and kill the AG VPN

### Actual Behavior

After some time, the AG VPN closes and Adguard keep running

**Comment by ArrayKamko** [comment]
I sent the Log report of both apps to devteam@adguard.com

This happened several times from 19:20 pm to 19:32 pm

Even turning on the watchdog still does not change
But if I use VPN alone, it won't be closed even for days

**Comment by TPS** [comment]
https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/252#issuecomment-2149523625 is essentially this, also.

**Comment by ESurina** [comment]
Send us your system logs please. Here's how to do it: https://adguard.com/kb/adguard-for-android/solving-problems/logcat/
Reproduce the issue, then remember the exact time when it happened and send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
- mention the `465` number in the subject
- specify the exact time when the issue occurred

**Comment by ArrayKamko** [comment]
Done , Send @ESurina 

VPN was killed several times today Most of the time it was when the phone was not in use (although it used to be killed in time of use ) with Wi-Fi and Data Mobile network
The last time this happened again, I think it was around **19:30**

**Comment by ESurina** [comment]
May I know what com.vivo.abe is on your phone? Perhaps there is something else you can configure in this optimizer

**Comment by ArrayKamko** [comment]
> May I know what com.vivo.abe is on your phone? Perhaps there is something else you can configure in this optimizer

Apparently, it is related to the Vivo company itself and the customized Android ( Funtouch 14 )
Because I don't have root access, they can't be deleted
Apparently, it is related to Smart Engine and AiEngine apps

![photo_2024-07-11_12-33-11](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/13505498/7a801d6d-cd70-454c-8b2f-8cbbc7788ab9)
![photo_2024-07-11_12-33-07](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/13505498/977b04fd-067f-4add-8f5e-a849c19fbbbc)
![photo_2024-07-11_12-33-02](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/13505498/8d4963bf-e1ae-404f-b838-292149d06d76)

**Comment by ArrayKamko** [comment]
It is said here that deleting this app is Unsafe (this can bootloop the phone or break extremely important features).

https://github.com/0x192/universal-android-debloater/issues/820

**Comment by ESurina** [comment]
The problem is with your phone's system. We can advise you to try using watchdog.

**Comment by ArrayKamko** [comment]
> Even turning on the watchdog still does not change

As I said, turning on the watchdog does not change anything
