### ISSUE TITLE
Adguard and Adguard VPN compatibility mode 

### ISSUE THREAD

**Issue by D-Flowers** [AdguardTeam/AdGuardVPNForAndroid#466]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.8.3

### Operating mode

VPN

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

https://adguard-dns.io/en/dashboard/settings/8efd5c8d

### Environment

```markdown
- OS: Android 12
- Device: Chromecast with Google TV
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1.Install and connect to Adguard ad blocker for Android TV, select private DNS server and include all features for ad blocking 
2.Install Adguard VPN from the Play Store, login and also connect to the same DNS server 
3.Pick the fastest server location and connect to it

### Expected Behavior

It sometimes will automatically display confirmation that they're working in compatibility mode.

### Actual Behavior

One often will override the other and function like if you attempted to run any two VPN services at the same time on Android.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by maxikuzmin** [comment]
@D-Flowers could you please clarify how you check that one of the apps stops working? 
How often does it happen and for how long? 
I checked this, but the [test site](https://adguard.com/en/test.html) shows both apps as "Running", including the selected DNS server that I also selected in both apps

**Comment by maxikuzmin** [comment]
@D-Flowers any news?

**Comment by maxikuzmin** [comment]
@D-Flowers for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by D-Flowers** [comment]
I apologize,I actually forgot I even opened the issue. That was when Adguard was first released for Android TV and since then compatibility mode seems to function pretty well. One will still kick the other sometimes so it's not perfect but it's much better. What would be great if Tasker could be integrated into it like the regular Android version but I'm sure there are reasons why it lacks the function at least for now.

**Comment by maxikuzmin** [comment]
@D-Flowers glad to hear that. I think it's too early for Tasker on Android TV. I don't see it in the Play store for TV, I don't think it's there

**Comment by D-Flowers** [comment]
> @D-Flowers glad to hear that. I think it's too early for Tasker on Android TV. I don't see it in the Play store for TV, I don't think it's there
> 

It's not, I do have and use it for multiple reasons but I also have a direct licensed version which doesn't need to be validated though Google Play so I guess it's not really viable at the moment. Thank you and I suspect both apps will improve as time passes.

**Comment by maxikuzmin** [comment]
@D-Flowers absolutely. Thanks, we'll look into it
