### ISSUE TITLE
Feature Request for AdGuard VPN

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForAndroid#469]
### Issue Details

There should be an option in AdGuard VPN that enables users to configure AdGuard VPN in built-in Android's Settings without using the App.

**Comment by Versty** [comment]
@suggest132 Currently, you can configure `Always-on VPN` and `Block connections without VPN` from the system settings, but for other application settings, the Android system does not provide a place from where they can be applied manually.

**Comment by ghost** [comment]
@Versty
@adguard
@adguard-bot
Please look here,
https://windscribe.com/features/config-generators/
The Windscribe VPN allows its pro users to configure their VPN in Android's Settings if they don't want to use the app and there exist a settings in Android for doing so.
