### ISSUE TITLE
Приложение для Андроид

### ISSUE THREAD

**Issue by Stanis-1** [AdguardTeam/AdGuardVPNForAndroid#470]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

Последняя версия для Андроид

### Operating mode

VPN

### Which DNS server do you use?

Default

### DNS protocol

None

### Environment

```markdown
- OS:Android 7.1.1
- Device:Asus Zenfone 4 Max (Модель: ZC520KL)
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. Не получается Войти в мой Аккаунт приложения AdGuard VPN через Андроид!
2. Выдаёт ошибку и пишет: Попробуйте ещё раз или напишите в Поддержку!
3.

### Actual Behavior

Ваше Приложение для Андроид не даёт мне войти в него со своего Аккаунта! Выдаёт ошибку и пишет: Попробуйте ещё раз или обратитесь в Поддержку! Вот я и обращаюсь к Вам!

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ESurina** [comment]
Убедитесь, пожалуйста, что на вашем устройстве правильно выставлены время и дата.
Если все верно, то для диагностики и решения Вашей проблемы, нам понадобятся логи приложения AdGuard.

Соберите и отправьте указанные файлы, используя данную инструкцию:

1. Включите подробный уровень логирования:
7 раз нажмите на заголовок *Войти или зарегистрироваться* -> *Уровень логирования -> Экстремальный*
2. Воспроизведите проблему, запомните точное время воспроизведения
3. Экспортируйте логи:
7 раз нажмите на заголовок *Войти или зарегистрироваться* -> *Экспортировать логи и информацию о системе*
4. Отправьте файл на почту [devteam@adguard.com](mailto:devteam@adguard.com):
    - упомяните `470` номер в заголовке письма
    - укажите точное время воспроизведения проблем

**Comment by ESurina** [comment]
Получилось ли решить проблему с помощью настройки даты и времени? Если нет, то напоминаю, что нам нужны логи приложения AdGuard.

**Comment by Stanis-1** [comment]
Проблема не в Вашем приложении, а в моём старом смартфоне, потому что на более новом смартфоне у меня установилось Ваше приложение и всё прекрасно работает! Так что спасибо! А на счёт логов, то я не умею вытаскивать логи из андроидов.
