### ISSUE TITLE
Streaming services don't work 

### ISSUE THREAD

**Issue by wadie92** [AdguardTeam/AdGuardVPNForAndroid#473]
https://www.tvnz.co.nz
Television New Zealand is free streaming service with new Zealand  locations doesn't work 

Australia location 
https://www.9now.com.au/ 
https://iview.abc.net.au/
https://7plus.com.au/
https://www.sbs.com.au/ondemand/
They are all free streaming services , which they were working with my previous vpn. 

https://www.stan.com.au/ 
Doesn't work it was working with my previous vpn .

USA locations
 
https://starz.com 
doesn't work  on all USA locations

Hopefully you will fix it so i don't need another VPN I've got 5 years subscriptions on adguardvpn with adguard dns and lifetime adguard ad blocker . 
Kind regards

**Comment by maxikuzmin** [comment]
@wadie92 we have a list of supported streaming services and we are expanding it over time.
We are trying to ensure that streaming is available at least in certain locations (e.g. many US streaming services work with US locations)

I've added streaming to our list, we'll look into adding supported locations for your streaming list, thanks!

**Comment by wadie92** [comment]
I'm sure a lot of people want to switch to adguard vpn because it is working perfectly with adguard blocker but the problem of not supporting all streaming services keeps them away from adguard vpn .  Hopefully you will be able to fix it soon. Thx
