### ISSUE TITLE
AdGuard VPN for Android coudn't find any location while Windows version works well

### ISSUE THREAD

**Issue by V-G62** [AdguardTeam/AdGuardVPNForAndroid#479]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.9.1

### Operating mode

VPN

### Which DNS server do you use?

Default

### DNS protocol

Regular

### Environment

```markdown
- OS: Android 14
- Device:Samsung S21FE
- OS: Android 13
- Device: Android TV Box SharksTrade Mediaroom
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. Start app an login
2. Try to connect
3. Try to search locations
4. Try to do the same steps with the same settings on Windows notebook

### Actual Behavior

Step2 - infinitely waiting
Step3  -  no locations
Step4 - OK, connected, many locations

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@V-G62 Hi! 

We would like to take a look at the logs from your device. 
Please follow the steps below: 

1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Extended*.

2. Reproduce the problem, then remember the exact time it happened.

3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*.

4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `479` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by V-G62** [comment]
Hi,
I've sent log to to qa@adguard.com 2 days ago.
Now additional information. When  I tried to connect my smartphone via wifi (to router), I received the message "no found location". Then I switched off wifi and tried via my mobile operator, AdGuard found many locations immediately.

**Comment by Versty** [comment]
@V-G62 Thank you for additional details. 
We have received log files from your device.

**Comment by Versty** [comment]
@V-G62 Unfortunately, not all the necessary information has been logged, so we need a new log record. 

We would like you to follow the updated steps: 
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Extended*.

2. **Restart the application completely** 

2. Reproduce the problem, then remember the exact time it happened.

3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*.

4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `479` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by V-G62** [comment]
Couldn't reproduce the problem last two days.
Maybe, the bug was on server side, and AdGuard team fixed it?

**Comment by Versty** [comment]
@V-G62 
Could be the case. If the problem reoccurs please reopen this issue and let me know.

**Comment by V-G62** [comment]
Hi,
Please reopen this case, I'll send two logs to qa@adguard.com: from 05.10.24 I can't connect the server, and from 06.10.24 I reset the phone, but couldn't find locations. The Windows version works well.

**Comment by Versty** [comment]
@V-G62 Thank you for providing new files! 
We are looking into this.

**Comment by Versty** [comment]
@V-G62 Does the issue still persist with Adguard VPN for Android 2.10.1?

**Comment by V-G62** [comment]
No, I don't view this problem now.
