### ISSUE TITLE
AdGuard VPN Server Is Not Responding

### ISSUE THREAD

**Issue by technomaniac90** [AdguardTeam/AdGuardVPNForAndroid#48]
### Prerequisites

- [✓ ] I am running the latest version
- [✓ ] I checked the documentation and found no answer
- [ ✓] I checked to make sure that this issue has not already been filed

### Issue Details

AdGuard VPN server is not responding. It shows "Location has not been selected. Perhaps, the network is unavailable. Please try again later". 

The problem is, my network is working just fine.

- **AdGuard VPN version:**
  - v1.0.259
- **VPN mode:**
  - Compatibility mode
- **Device:**
  - Samsung Galaxy SM-N950F
- **Operating system and version:**
  - Android 9
- **Root access:**
  - No 

### Expected Behavior

I was expecting the VPN connection would succeed.

### Actual Behavior

Toast message appears showing, "Location has not been selected. Perhaps, the network is unavailable. Please try again later"

### Screenshots

![Screenshot_20201118-193539_AdGuard VPN](https://user-images.githubusercontent.com/74660651/99532306-0992e600-29df-11eb-838a-51403b2d9c47.jpg)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
Sorry for this, maintainance, the issue will go away in a moment
