### ISSUE TITLE
There is no authorization via QR code in the AdGuard VPN app on Android TV.

### ISSUE THREAD

**Issue by ElenaManukyan** [AdguardTeam/AdGuardVPNForAndroid#488]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.10.42

### Operating mode

VPN

### Which DNS server do you use?

None

### DNS protocol

None

### Environment

```markdown
- OS: Android TV
- Device: MiBox4
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. Open AsGuard VPN on your TV. 
2. Scan the QR code and log in to your AdGuard VPN account on your phone

### Expected Behavior

You must log in to your account on the TV.

### Actual Behavior

There is no sign-in. The page on the TV does not change.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Authentication via QR code in AdGuard VPN in the Android TV app

**Comment by Versty** [comment]
@ElenaManukyan Hi! 
Please force stop the application in the system settings and try to login via QR code again.

**Comment by Versty** [comment]
@ElenaManukyan 
Any updates?

**Comment by Versty** [comment]
Seems like resolved. 
If not, please reopen this issue.
