### ISSUE TITLE
Ring app errors when VPN is connected

### ISSUE THREAD

**Issue by AnthonyBe** [AdguardTeam/AdGuardVPNForAndroid#49]
### Issue Details
When VPN is connected,  the Ring app cannot connect to its cloud service. 
When VPN is disconnected,  the Ring app works fine. 
https://play.google.com/store/apps/details?id=com.ringapp

- **AdGuard VPN version:**
  -  1.0 (259)
- **VPN mode:**
  - SOCKS5
- **Device:**
  -   Samsung Galaxy S10+ and Samsung Tablet S5e
- **Operating system and version:**
  - Android 10
- **Root access:**
  - No 

### Expected Behavior

Ring App connects to cloud service and displays my devices
### Actual Behavior

Error: Couldn't load your locations.  We're having trouble loading your Location information. Please try again.
### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20201127-222759_Ring](https://user-images.githubusercontent.com/17214552/100444955-69d10880-3100-11eb-8993-c5ed59219771.jpg)

![Screenshot_20201127-222900_Ring](https://user-images.githubusercontent.com/17214552/100444986-735a7080-3100-11eb-8caf-0cabbdfe476d.jpg)

</details>

**Comment by artemiv4nov** [comment]
@AnthonyBe Hello!

Sorry for the late response.
Can you test again on the latest Play Store build?

**Comment by AnthonyBe** [comment]
Seems to be fine now using AG VPN v1.2 beta 1 (25)
