### ISSUE TITLE
Kill switch for AdGuard VPN for Android TV

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForAndroid#490]
### Issue Details

There is no kill switch feature for AdGuard VPN for Android TV.

### Proposed solution

Add a kill switch for AdGuard VPN for Android TV.

**Comment by ESurina** [comment]
Unfortunately, we cannot add this feature because the operating system does not support it.

**Comment by ghost** [comment]
@ESurina you may want to remove it from the website in that case.

> We're always working to make AdGuard VPN even better. Soon, the Android TV version of AdGuard VPN will have popular features from our mobile and desktop versions, such as Kill Switch and DNS leak protection.

https://adguard-vpn.com/en/android-tv/overview.html

**Comment by serenacreek** [comment]
Surfshark VPN provides a kill switch on their android TV application. It looks like the operating system does support this feature. May we please reopen this issue? 

https://support.surfshark.com/hc/en-us/articles/360024352553-How-to-set-up-Surfshark-on-Android-TV

**Comment by nicpas05** [comment]
Please add KillSwitch toAndroidTV App. Theres no technical barrier to do so.
