### ISSUE TITLE
Переменчива скорость и большой пинг / Variable speed and high ping

### ISSUE THREAD

**Issue by AlexeyPMozgovoy** [AdguardTeam/AdGuardVPNForAndroid#499]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.10.145

### Operating mode

Integration with AdGuard

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### Custom DNS

⚬ ⚬ ⚬

### Environment

```markdown
∘ **Операционная система**: Android 13.
∘ **Устройство**: Blackview Shark 8.
∘ **Интернет-провайдер**: ...
∘ **Регион**: РФ.
∘ **Время начала проблемы**: с момента покупки лицензии на год продукта «AdGuard VPN» ((30.10.2024, 19:17 по Московскому времени (МСК, UTC+3)).

**_ENGLISH_**:
∘ **Operating System**: Android 13.  
∘ **Device**: Blackview Shark 8.  
∘ **Internet Provider**: ...
∘ **Region**: Russia.
∘ **Time the issue began**: Since purchasing the one-year license for the product «AdGuard VPN» (30.10.2024, 19:17 Moscow Time (MSK, UTC+3)).
```

### Root access

- [ ] yes, I have it

### Issue Details

 Подключение к «AdGuard VPN» в любых режимах и конфигурациях (будь-то «Интеграция», «VPN», любой протокол и так далее).

 **_ENGLISH_**:
 Connection to «AdGuard VPN» in any modes and configurations (whether «Integration», «VPN», any protocol, and so on).

### Expected Behavior

 Хорошая скорость (как «скачать», так и «загрузить»), быстрая загрузка веб-страниц в веб-браузерах («Яндекс Браузер», «Soul Browser» и так далее), воспроизведение видео на «YouTube» в хорошем качестве (от 1080p), пинг в пределах разумного (до +/- 50 мс).

 **_ENGLISH_**:
 Good speed (both «download» and «upload»), fast loading of web pages in web browsers («Yandex Browser», «Soul Browser», etc.), video playback on «YouTube» in good quality (from 1080p), ping within reasonable limits (up to +/- 50 ms).

### Actual Behavior

 Постоянно скачет скорость ((то она +/- 3,5 MB/s (нормально), то опускается чаще около 1 MB/s (плохо)), долго загружаются веб-страницы, плохо грузит видео на «YouTube», очень большой пинг (около 100+ мс).

 **_ENGLISH_**:
 The speed constantly fluctuates (sometimes it's around +/- 3.5 MB/s, which is normal, but more often it drops to about 1 MB/s, which is poor), web pages take a long time to load, videos on «YouTube» load poorly, and there is a very high ping (around 100+ ms).

### Screenshots

 Некоторые проверки скорости и пинга с помощью «Speedtest» (немного, так как я не могу постоянно 
измерять; показывает правильно, так как ощущаю эту изменчивость при сёрфинге в интернете) / / / **_ENGLISH_** — Some speed and ping tests using «Speedtest» (a few, as I cannot measure constantly; it shows correctly, as I experience this variability while surfing the internet):

<details>
 <summary>Скриншоты/Screenshots </summary>

 ![Screenshot_20241104-004151](https://github.com/user-attachments/assets/7de138bf-5145-4832-9f01-a6b93c8e8fbe)

 ![Screenshot_20241103-204828](https://github.com/user-attachments/assets/a308f164-aca0-4f81-85f1-9b1b38ea427f)

 ![Screenshot_20241103-204907](https://github.com/user-attachments/assets/37b1f8f4-e060-4783-a3b3-98751a660331)

 ![Screenshot_20241103-204932](https://github.com/user-attachments/assets/a9cbef22-2711-4e80-8282-1b77d1fd193f)

 ![Screenshot_20241103-205000](https://github.com/user-attachments/assets/2007d536-1376-4704-b849-7d32d82ee216)

 ![Screenshot_20241103-205026](https://github.com/user-attachments/assets/3d6bd3fa-291b-4122-9017-b332d594ce32)
</details>

### Additional Information

 Дать ссылку не могу на DNS, так как использую персональный от «AdGuard DNS». Без подключения к «AdGuard VPN» со скоростью всё хорошо (+/- 4 MB/s) и пинг нормальный (доходит до +/- 20 мс, но чаще всего меньше).

  **_ENGLISH_**:
I cannot provide a link to the DNS, as I use a personal one from "AdGuard DNS". Without connecting to "AdGuard VPN", the speed is fine (+/- 4 MB/s) and the ping is normal (reaching up to +/- 20 ms, but most often less).

**Comment by biomednet** [comment]
Приватный DoH на роутере Кинетик. Связь смартфона через вай-фай.
Исходная скорость около 300 Мб/с. 
Пропускная способность вайфай - 1Гб/с аппаратно. 
Скорость ко всем серверам имеет начальный всплеск максимума, потом падает. Часто бывает, 322633 тест нельзя завершить. Скорость неустойчивая при просмотре допустим, Ютуба. Смотришь фильм, все ок, а потом раз, и обрыв. 
Пока не видел ни одного сервера с устойчивой большой скоростью. Netorn Москва.

**Comment by AlexeyPMozgovoy** [comment]
Хочу ещё добавить, что показывает неправильно пинг в «AdGuard VPN». Например, показывает пинг 36 мс, а проверяешь с помощью «Speedtest» и оказывается, что на самом деле 121 мс / / / _**ENGLISH**_ — I would also like to add that the ping in «AdGuard VPN» is displayed incorrectly. For instance, it shows a ping of 36 ms, but when you check using «Speedtest», it turns out to be actually 121 ms:
<details>
 <summary>Скриншоты/Screenshots </summary>
 
 ![Screenshot_20241104-132541](https://github.com/user-attachments/assets/5ec4970a-2b4a-485a-9f5f-28ae0e0ec86b)
 
 ![Screenshot_20241104-132647](https://github.com/user-attachments/assets/2e208328-0b48-460d-bb63-115ad5d1c9c6)
</details>

**Comment by AlexeyPMozgovoy** [comment]
И ещё, особенно вечером заметно понижение скорости обычно. Хаотично. И пинг у меня большой уже несколько дней держится, не падает / / / **_ENGLISH_** — And also, especially in the evening, there is usually a noticeable decrease in speed. Erratic. And my ping has been high for several days now, not dropping.

**Comment by ESurina** [comment]
Здравствуйте!
Благодарим за обращение.
В последние несколько дней мы получили ряд обращений от пользователей с сообщениями о проблемах с низкой скоростью соединения при использовании нашего VPN.
Проблема связана с продолжающимися попытками ограничить работу VPN на территории России. Вторая причина — блокировка YouTube. Пользователи вынуждены всё чаще использовать VPN для просмотра видео, что приводит к кратному увеличению нагрузки на серверы.
В самое ближайшее время скорость будет восстановлена. Вы можете помочь нашей команде, собрав немного информации:
• Какую локацию VPN используете чаще всего?
• Есть ли проблема на других локациях?
• Нелишними будут логи из приложения, собранные по следующей инструкции:
1. Включите ведение расширенных логов:
*Настройки -> Основные -> Расширенные -> Уровень логирования -> Расширенный*.
2. Воспроизведите проблему, а затем запомните точное время ее возникновения.
3. Соберите логи:
*Настройки -> Основные -> Расширенные -> Экспортировать логи и информацию о системе*.
4. Отправьте этот файл на [qa@adguard.com](mailto:qa@adguard.com):
    - в теме письма укажите ключевое слово `[android]` и `ISSUE_NUMBER`
    - укажите точное время, когда возникла проблема

Приносим извинения за временные неудобства. Делаем всё возможное, чтобы как можно скорее улучшить ситуацию.

**Comment by AlexeyPMozgovoy** [comment]
> Здравствуйте!
> Благодарим за обращение.
> В последние несколько дней мы получили ряд обращений от пользователей с сообщениями о проблемах с низкой скоростью соединения при использовании нашего VPN.
> Проблема связана с продолжающимися попытками ограничить работу VPN на территории России. Вторая причина — блокировка YouTube. Пользователи вынуждены всё чаще использовать VPN для просмотра видео, что приводит к кратному увеличению нагрузки на серверы.
> В самое ближайшее время скорость будет восстановлена. Вы можете помочь нашей команде, собрав немного информации:
> • Какую локацию VPN используете чаще всего?
> • Есть ли проблема на других локациях?
> • Нелишними будут логи из приложения, собранные по следующей инструкции:
> 1. Включите ведение расширенных логов:
> *Настройки -> Основные -> Расширенные -> Уровень логирования -> Расширенный*.
> 2. Воспроизведите проблему, а затем запомните точное время ее возникновения.
> 3. Соберите логи:
> *Настройки -> Основные -> Расширенные -> Экспортировать логи и информацию о системе*.
> 4. Отправьте этот файл на [qa@adguard.com](mailto:qa@adguard.com):
>     - в теме письма укажите ключевое слово `[android]` и `ISSUE_NUMBER`
>     - укажите точное время, когда возникла проблема
> 
> Приносим извинения за временные неудобства. Делаем всё возможное, чтобы как можно скорее улучшить ситуацию.

**Comment by AlexeyPMozgovoy** [comment]
> Проблема связана с продолжающимися попытками ограничить работу VPN на территории России. Вторая причина — блокировка YouTube. Пользователи вынуждены всё чаще использовать VPN для просмотра видео, что приводит к кратному увеличению нагрузки на серверы.
> В самое ближайшее время скорость будет восстановлена. Вы можете помочь нашей команде, собрав немного информации:
> • Какую локацию VPN используете чаще всего?
> • Есть ли проблема на других локациях?
> • Нелишними будут логи из приложения, собранные по следующей инструкции:
> 1. Включите ведение расширенных логов:
> *Настройки -> Основные -> Расширенные -> Уровень логирования -> Расширенный*.
> 2. Воспроизведите проблему, а затем запомните точное время ее возникновения.
> 3. Соберите логи:
> *Настройки -> Основные -> Расширенные -> Экспортировать логи и информацию о системе*.
> 4. Отправьте этот файл на [qa@adguard.com](mailto:qa@adguard.com):
>     - в теме письма укажите ключевое слово `[android]` и `ISSUE_NUMBER`
>     - укажите точное время, когда возникла проблема

 Здравствуйте, ESurina! 🤗
 Спасибо за ответ! ❤️ 
 В принципе, я на это ставку и делал, что РКН блокирует, плюс нагрузка.
 Использую чаще всего ту локацию, у которой «меньше» всего пинг, поэтому точную какую-то сказать не могу, но обычно это Финляндия, Швеция. На остальных локациях тоже самое. Логи уже отправил на указанную Вами почту.👌
 
 **_ENGLISH_**:
 Hello, ESurina! 🤗  
 Thank you for your response! ❤️  
 In principle, I was counting on this, that RKN blocks it, plus the load.  
 I usually use the location with the «least» ping, so I can't specify exactly, but it's usually Finland or Sweden. It's the same for other locations. I have already sent the logs to the email you specified.👌

**Comment by ESurina** [comment]
Спасибо вам за предоставленную информацию!
