### ISSUE TITLE
Unable to log in to AdGuard VPN on TV 

### ISSUE THREAD

**Issue by Eksol** [AdguardTeam/AdGuardVPNForAndroid#501]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.10.1

### Operating mode

VPN

### Which DNS server do you use?

None

### DNS protocol

None

### Environment

```markdown
- OS: Android 11 ATV (slimbox)
- Device: tanix tx3 mini plus (s905w2)
```

### Root access

- [X] yes, I have it

### Issue Details

Steps to reproduce:
1. Open ATV version androidvpnadguard
2. Try to login to your account

### Actual Behavior

Unable to log into your account. Connection error.

### Screenshots

<details><summary>Screenshot 1</summary>

![photo_2024-11-05_21-20-28](https://github.com/user-attachments/assets/439e3ad5-9a41-4ad1-83d9-8f9554a796e6)
![photo_2024-11-05_21-20-38](https://github.com/user-attachments/assets/6b7a8f27-ac43-4cd2-8bbe-cdd9d6ea2f0a)

</details>

### Additional Information

There are 2 set-top boxes installed in the house on the same network.

The first set-top box has a smart TV on a s912 processor - no problems
The second set-top box has a smart TV on a s905w2 processor - there are problems

**Comment by Versty** [comment]
@Eksol Please make sure that you have set the time on the TV box according to real time in your time zone. 

Then force stop the AdGuard VPN application from system settings and launch it again. 
If the time set correctly, the QR code should appear on `Войти или зарегистрироваться` screen.

**Comment by Eksol** [comment]
> Please make sure that you have set the time on the TV box according to real time in your time zone.
> 
> Then force stop the AdGuard VPN application from system settings and launch it again. If the time set correctly, the QR code should appear on `Войти или зарегистрироваться` screen.

I checked the time. It is correct. I tried to set it to Moscow, it did not help.

**Comment by Versty** [comment]
@Eksol Have you also checked the date?

**Comment by Eksol** [comment]
> Have you also checked the date?

yes, correct data, correct time, correct time zone

**Comment by Versty** [comment]
@Eksol If the issue still persists, we would like to take a look at the system bug report from your device. 

Please follow below steps: 

1. Install [adb](https://developer.android.com/tools/releases/platform-tools#downloads) to your PC.
2. Unlock developer options and enable USB debugging on your TV as explained in [this article](https://www.xda-developers.com/how-to-access-developer-options-amazon-fire-tv/).
3. Make sure that your TV and PC use the same network, and connect your TV to PC using the adb command.
`adb connect xxx.xxx.xxx.xxx` where xxx.xxx.xxx.xxx is IP address of your TV.
4. Launch AdGuard VPN and reproduce the issue, note the time of reproduction.
5. Use the `adb bugreport` command to collect bug report.
6. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `501` number in the subject of your email
    - specify the exact time when the issue occurred

**Comment by Eksol** [comment]
> @Eksol If the issue still persists, we would like to take a look at the system bug report from your device.
> 
> Please follow below steps:
> 
> 1. Install [adb](https://developer.android.com/tools/releases/platform-tools#downloads) to your PC.
> 2. Unlock developer options and enable USB debugging on your TV as explained in [this article](https://www.xda-developers.com/how-to-access-developer-options-amazon-fire-tv/).
> 3. Make sure that your TV and PC use the same network, and connect your TV to PC using the adb command.
>    `adb connect xxx.xxx.xxx.xxx` where xxx.xxx.xxx.xxx is IP address of your TV.
> 4. Launch AdGuard VPN and reproduce the issue, note the time of reproduction.
> 5. Use the `adb bugreport` command to collect bug report.
> 6. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
>    
>    * include `[android]` keyword and `501` number in the subject of your email
>    * specify the exact time when the issue occurred

Bug report was sent

**Comment by Eksol** [comment]
Will there be a correction?

**Comment by Versty** [comment]
@Eksol We are investigating. 

Have you tried to restart the TV after setting time to Moscow?

**Comment by Eksol** [comment]
> Have you tried to restart the TV after setting time to Moscow?

Not work...

**Comment by Eksol** [comment]
> @Eksol We are investigating.
> 
> Have you tried to restart the TV after setting time to Moscow?

any news?

**Comment by Eksol** [comment]
Are you going to solve the problem?

**Comment by Versty** [comment]
@Eksol We are looking for exact cause at the moment. 
Is your problematic TV device connected to the Internet via Wi-Fi or Ethernet?

**Comment by Eksol** [comment]
> We are looking for exact cause at the moment.
> Is your problematic TV device connected to the Internet via Wi-Fi or Ethernet?

wifi

**Comment by Versty** [comment]
@Eksol We tend think that this problem is caused by some limitations from ISP. 
If the problem still persists, please close AdGuard VPN app completely (the best solution is Force stop the app from system settings), then wait for a few hours. Launch and try to log in one more time.

**Comment by Eksol** [comment]
> We tend think that this problem is caused by some limitations from ISP.
> If the problem still persists, please close AdGuard VPN app completely (the best solution is Force stop the app from system settings), then wait for a few hours. Launch and try to log in one more time.

It was clear that the problem was the provider's limitation. When turning on a third-party VPN, adguardvpn started working normally. I expected that you would find a solution to this problem. If you cannot solve this problem, then your product is not worth the money.

**Comment by Versty** [comment]
@Eksol Unfortunately, If you are able to log in using third-party VPN, then that confirms the restrictions from ISP.

If you face the same problem next time, here is two options you can try:
1. Clear app data & caches, then launch in a few hours.
2. Close the app completely (Force stop the app from system settings), wait for a few hours, then launch again.

**Comment by Eksol** [comment]
> * Clear app data & caches, then launch in a few hours.
> * Close the app completely (Force stop the app from system settings), wait for a few hours, then launch again.

Why does the app work on my smartphone but not on my TV? Android is installed in both places.

**Comment by Versty** [comment]
@Eksol 
1. Smartphone can use cellular data or wifi. Even if your ISP provider restricts VPN service usage, you still can log in via cellular data. 
2. Caches. Basically after unsuccessful login attempt (due to ISP restrictions), the caches should be cleared. On smartphone mush easier to clear app caches, than on Android TV.
