### ISSUE TITLE
Adguard VPN для Android TV 5.0+

### ISSUE THREAD

**Issue by ArturD94** [AdguardTeam/AdGuardVPNForAndroid#505]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Существует ли последняя версия Adguard VPN для Android TV версии 5.0+?
Пытаясь установить последнюю версию Adguard VPN для Android, выдают ошибку установки. Пытался установить разные версии и пришел к выводу что на моем TV работает только версии для Android 5.0+. Версия которая запускается на TV - 2.0.154, но она как будто не приспособлена под TV формат, не могу зайти даже в выбор локации. Есть ли решение в такой проблеме?

**Comment by ESurina** [comment]
Мы начали поддерживать Android TV только с версии 2.2 и она доступна для Android 7.0+
Поэтому, к сожалению, невозможно установить AdGuard VPN на Android TV версии 5.0.
