### ISSUE TITLE
US New York Server Connection to China?

### ISSUE THREAD

**Issue by DrSuSE** [AdguardTeam/AdGuardVPNForAndroid#509]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

My phone has not been able to connect to the US/New York server for a while when I am at work. I am on the east coast and typically connect to NY since it shows up as the fastest for me.

I decided to look at the office firewall logs and see why and I saw that anytime I try to connect to US/NY, Adguard VPN is trying to make a connection to myworkdaycdn.com.cn which is blocked.

Seems sort of alarming that it would try to connect to a Chinese domain.

**Comment by ameshkov** [comment]
Hello,

AdGuard VPN when establishing a connection to the VPN server makes the traffic look like a regular HTTPS connection to a real existing domain. In fact this is a VPN connection.

The reason for that is to make the VPN traffic harder to distinguish from web traffic. These domain names are often rotated so one day it could be that, the other day it could be a different one. This domain name will soon be rotated out.

> myworkdaycdn.com.cn which is blocked

Could you please tell us how is it blocked? Is it on some public blocklist?
We could take this into account and avoid rotating in domains from public blocklists.

**Comment by DrSuSE** [comment]
It was on the default blocklist on our Sonicwall hardware appliance/firewall.  It is unclear to me if this is a list generated by Sonicwall or by our vendor.

**Comment by ameshkov** [comment]
Got it, thank you!

As I can see the domain is already rotated out so the problem should go away. This is an interesting issue though, we'll think about ways to solve it. Maybe depending on the user location we should use different pools of these "front" domains, something that's less likely to end up on a blocklist.

**Comment by DrSuSE** [comment]
I can confirm that I  was able to make a connection to NY now and I do feel better with you explanation.  I am not sure how long the domains remain in rotation, today was not the first time I had this issue (but I don't know if previous instances were the same domain or others in the same situation).  I will report them if it happens again.
