### ISSUE TITLE
Add quick shortcut on Android 

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForAndroid#54]
Add quick shortcut (press the application in the application tray) on Android

- Add shortcut to connect to VPN
- Add shortcut to disconnect VPN

**Comment by APKLift** [comment]
There lot vpns for android, free, simple use and safe
apktom is most good apk store

https://apktom.com/special/VPNs_for_PUBG/

**Comment by zzebrum** [comment]
dup of #75
