### ISSUE TITLE
Allow LAN connection while connected to VPN

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForAndroid#56]
When connecting to the VPN add the function of allowing the use of LAN services on the internal network

(Example: Chromecast, screen mirroring on smart tv and printer)

**Comment by ameshkov** [comment]
Hm, in theory they should be allowed by default.

@artemiv4nov don't we have LAN IPs on the "excluded routes" by default?

**Comment by artemiv4nov** [comment]
Well, we have the following IPv4 exclusions:
```
// Reserved subnets
0.0.0.0/8
10.0.0.0/8
100.64.0.0/10
172.16.0.0/12
192.0.0.0/24
192.168.0.0/16
224.0.0.0/4
240.0.0.0/4
255.255.255.255/32

// T-Mobile wi-fi calling (#233)
208.54.0.0/16

// AT&T wi-fi calling
129.192.166.0/24

// UK EE wi-fi calling (#582)
109.249.0.0/16

// Sprint wi-fi calling (#939)
68.31.26.0/24

// Verizon wi-fi calling (#1321)
141.207.0.0/16

// Orange PL wi-fi calling (#1796)
217.116.96.0/20
```

**Comment by eduardoaddad** [comment]
could have a function to disable or enable in the settings
