### ISSUE TITLE
Disney + does not work on servers in countries supported by the disney platform

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForAndroid#58]
Disney + does not work on servers on servers in the USA, Canada, Brazil, the Netherlands, France, Spain, Italy, Germany and others.

**Comment by TheHasagi** [comment]
Some streaming services are detecting VPN and blocking that IP, we are working on it to avoid such issues. The approximate time of solution in Q1 of 2021.
