### ISSUE TITLE
Superdrug app images won't load with Adguard VPN on. 

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardVPNForAndroid#66]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [✓] I am running the latest version
- [✓] I checked the documentation and found no answer
- [✓] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - v3.6.1
- **VPN mode:**
  - Compatibility with Adguard
- **Device:**
  - Google Pixel 5
- **Operating system and version:**
  - Android 11
- **Root access:**
  - No

### Expected Behavior

Images do not load in the app.

### Actual Behavior

When Adguard VPN is on, opening the superdrug app works fine but the images do not load. You can't see the products you're viewing. Turning off Adguard VPN will allow the images to be seen and turn Adguard VPN back on will keep the images as if it had been turned off.

### Screenshots

![Screenshot_20201220-211013.png](https://user-images.githubusercontent.com/72349391/104166523-db37f280-53f2-11eb-817d-a812a2a1bbf1.png)

![Screenshot_20201220-210805.png](https://user-images.githubusercontent.com/72349391/104166547-e2f79700-53f2-11eb-8e13-3f220887db3b.png)

You can see the images are not visible.

**Comment by TheHasagi** [comment]
@Perfectlynk 

Unable to reproduce this issue, can you try to change the server and check once more?

**Comment by Perfectlynk** [comment]
I have opened superdrug without the VPN. It's works fine. Turned on the VPN and changed the servers to USA and Poland. The images are still broken.

**Comment by TheHasagi** [comment]
@Perfectlynk 

Do the images loads with the only VPN enable?

In AdGuard for Android go to Settings - Apps management - Superdrug app disable ad blocking or protection for the whole app and try again.

**Comment by Perfectlynk** [comment]
No. None of the images load with Adguard VPN on. I turned off filtering in Adguard for superdrug, the images load fine.

**Comment by TheHasagi** [comment]
@Perfectlynk 

For now, when the filtering is disabled for Superdrug app does images loads fine in compatibility mode?

**Comment by Perfectlynk** [comment]
Yes. The images load fine.

**Comment by TheHasagi** [comment]
Closed.
