### ISSUE TITLE
PUBG Lite Issue

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/AdGuardVPNForAndroid#67]
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 1.0.1 (267)
- **VPN mode:**
  - Integration/VPN/SOCKS5
- **Device:**
  - ASUS ROG Phone 3, Yandex Phone (YNDX-000SB)
- **Operating system and version:**
  - v10 for ASUS ROG Phone 3 and v9 for Yandex Phone
- **Root access:**
  - No

### Expected Behavior

Ability to play PUBG Lite connected to the Singaporean server or other ones.

### Actual Behavior

Ability to play PUBG Lite connected only to the Brazilian server.

### Additional Information

HelpDesk ID – 3128557.

**Comment by artemiv4nov** [comment]
I'm closing this issue. If the problem will be relevant again, please reopen the issue.
