### ISSUE TITLE
Disconnect every 6 hours

### ISSUE THREAD

**Issue by AlfredSpijker** [AdguardTeam/AdGuardVPNForAndroid#7]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  1.0.136
- **VPN mode:**
  -  SOCKS5
- **Device:**
  -  OnePlus 6T
- **Operating system and version:**
  -  Android 10 / Oxygen 10.3.4
- **Root access:**
  -  No

### Expected Behavior

 
Permanent connection with VPN server
And auto-connect (option) after disconnection
### Actual Behavior

Is seems AndroidVPN disconnects every 6 hours after the first start / boot up.
Connection with server location Amsterdam, The Nethelands
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by TheHasagi** [comment]
@AlfredSpijker 

Hello!

Please, go to AdGuard VPN - Settings - Advanced settings - Logging level set to Debug. Try to reproduce the issue and tap on "Export logs and system info" - send them to devteam@adguard.com with an "AdGuard VPN Issue #7" subject.

**Comment by TheHasagi** [comment]
Closed due to no response.

**Comment by AlfredSpijker** [comment]
Please give your beta testers sone time to fullfil your requests, it's not our day job (at least not mine).
It was rather impossible to reproduce this problem, because it's happening to random. 
But I've found the culprit I think, it is your data limitation. I have a payed account since June 30th (used same email as here) and I found several toastmessages like this:

**AdGuard VPN:
AdGuard VPN can't create a VPN connection since you've reached traffic limit
2020-07-23 18:58:16**

So it's on the server site who broke up the connection. Will you please check and fix this? 

I think it is rather foolish to send such message about data limit reached as a toastmessage, because it's flashes just for some seconds and then disappears. It was just by coincide I noticed it one's and therefore checked the historie. 
Maybe you can changed it to a notification?

**Comment by AlfredSpijker** [comment]
Just happened again. It's in Dutch, but you got the message I assume.

Toastboodschap
AdGuard VPN:
AdGuard VPN kan geen VPN-verbinding maken omdat uw datalimiet is bereikt
2020-07-28 18:40:29

Proxy is niet verbonden
Tik om met de geselecteerde server te verbinden
2020-07-28 18:40:29


After manually started reconnection:

Proxy aan het verbinden met: Nederland, Amsterdam
Even geduld, je wordt snel verbonden met de proxy server
2020-07-28 18:41:13

**Comment by AlfredSpijker** [comment]
Maybe this helps to solve this disconnection problem:
Since July 29th there is always a disconnection (without auto reconnect) at 19.00 hrs (GMT+1) with the "reached data limit" message.

**Comment by ameshkov** [comment]
Might be a server-side issue, we're looking into it

**Comment by artemiv4nov** [comment]
@AlfredSpijker Hello! Can you re-check again, please? Perhaps, the problem can be gone already

**Comment by ameshkov** [comment]
Might be a server-side bug, we're looking into it

**Comment by AlfredSpijker** [comment]
> @AlfredSpijker Hello! Can you re-check again, please? Perhaps, the problem can be gone already

With "since July 29th" I ment every day after that date. The last disconnection was yesterday August 4th 19.00 hrs. I'll keep monitoring and reporting it.

**Comment by AlfredSpijker** [comment]
> @AlfredSpijker Hello! Can you re-check again, please? Perhaps, the problem can be gone already

@artemiv4nov @ameshkov still disconnected on August 5th and 6th at 19.00 hrs with the toastmessage "traffic limit 500 MB reached".

**Comment by ameshkov** [comment]
@AlfredSpijker could you please export the app logs and send them to devteam at adguard.com?

Logs can be exported in the advanced settings section

**Comment by AlfredSpijker** [comment]
> @AlfredSpijker could you please export the app logs and send them to devteam at adguard.com?
> 
> Logs can be exported in the advanced settings section

@ameshkov Logs send to devteam

**Comment by ameshkov** [comment]
Received, thank you!

**Comment by AlfredSpijker** [comment]
JFYI: updated to v. 1.0.155; bug still present

**Comment by ameshkov** [comment]
I am (almost) sure that the bug is on the server-side, but in order to catch it and prove it, we need to extend logging on the client and write what responses we receive from the server. Once it's done we'll post the details here.

**Comment by AlfredSpijker** [comment]
> I am (almost) sure that the bug is on the server-side, but in order to catch it and prove it, we need to extend logging on the client and write what responses we receive from the server. Once it's done we'll post the details here.

Do debug logs instead of the basic logs I send you, help?

**Comment by ameshkov** [comment]
A little, but we still don't see server responses there

**Comment by AlfredSpijker** [comment]
Running 1.0.243 now. I can confirm this issue is solved. Thanks for the fix!

**Comment by ameshkov** [comment]
Awesome, thanks for testing!
