### ISSUE TITLE
A question about filtering apps

### ISSUE THREAD

**Issue by Richelieu4771** [AdguardTeam/AdGuardVPNForAndroid#71]
Previously, in the beta version, it was stated that the torrent app cannot go through the VPN.
However, when I connect AdGuard 3.6 version and AdGuard VPN 1.0.1 version, I need to select the tunneling app in AdGuard.
So, now that "beta" has been removed, is the torrent app available through the VPN server?
In the AdGuard, I was able to choose it.

**Comment by TheHasagi** [comment]
@Richelieu4771 

Hello, this option is available only with a premium account.

**Comment by Richelieu4771** [comment]
@TheHasagi Sorry for the late further question. I have all of the premium accounts. But if I use AG VPN alone, I cannot use torrents through VPN yet. Are the premium accounts mentioned different types?

**Comment by TheHasagi** [comment]
@Richelieu4771 

Nope, if you have a VPN subscription you will be able to download via the torrent app. Could you please check that torrent app is in the filtering list in Apps management tab?

**Comment by Richelieu4771** [comment]
@TheHasagi

Oh, I can now choose torrent apps in standalone VPN mode. It wasn't selected until the question was written. Thanks for letting me check.
