### ISSUE TITLE
Connection is lost on OnePlus

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardVPNForAndroid#73]
1. AdGuard VPN + AdGuard operate in integration mode
2. At some point AdGuard VPN shows a notification that connection to the VPN server has been lost
3. It seems to be happening when the device is idle and nothing is happening

Probably, OnePlust limits connectivity of AdGuard VPN when the device is idle. The question is why it triggers "connection is lost" issue, AG VPN should be able to detect this.

**Comment by AlfredSpijker** [comment]
I reported this to Andrey. If you need any more information or testing, just let me know.

**Comment by AlfredSpijker** [comment]
Any news on this?
FYI I'm running 2 Android devices @home: my mobile phone OnePlus6T on 4G connection and my Android tablet PixelC with a WiFi connection. Both running latest beta versions of AdGuard and AdGuard VPN. Last weeks lots of VPN disconnects, mostly simultaneously on BOTH devices at the same time! So I don't think OnePlus is the main culprit. 
Please check your VPN server Amsterdam, the Netherlands.

**Comment by artemiv4nov** [comment]
So, we have some intermediate results, and you can test our `Pre Alpha` version.
I will give you the invite link. Can you please email me from your current Gmail account to devteam@adguard.com?

**Comment by AlfredSpijker** [comment]
Yesterday I got v. 1.2.35 (internal bèta) offered through the PlayStore. I installed it on both machines (OnePlus6T and Google PixelC) to test it the coming days. Stay tuned for the results...

**Comment by AlfredSpijker** [comment]
I have installed v. 2.0.13.  With the previous version, the problem reported above was almost completely solved. For testing, I've set all notifications to important with sound for this app. Now I notice that the app reports "Connecting" and then "Connected" many times within seconds. Is this a consciously implemented feature by you to keep the app continuously active?

**Comment by artemiv4nov** [comment]
@AlfredSpijker Hi!
The "VPN state" notification updates a few times because a lot of actions lead to VPN state change.
The default state for the "Service" notification channel is "Low priority" to not disturb users about each change of the VPN state.
So, I recommend you to disable sounds for this channel.

**Comment by AlfredSpijker** [comment]
> @AlfredSpijker Hi!
> The "VPN state" notification updates a few times because a lot of actions lead to VPN state change.
> The default state for the "Service" notification channel is "Low priority" to not disturb users about each change of the VPN state.
> So, I recommend you to disable sounds for this channel.

Thx for the quick reply and explaination. I thouht so. It indeed helps a lot to keep VPN-app running on my Pixel-C with only 4 Gb, where Android 8 try to kill it when memory is needed for other apps.
Switching the service notification to "low priority" now.

**Comment by TPS** [comment]
This is recurring on 1+ N200 5g recently.  Would something like https://github.com/AdguardTeam/AdguardForAndroid/issues/5320 for AGVPN help?
