### ISSUE TITLE
Add quick shortcuts on Android

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForAndroid#75]
Add quick shortcut (press the application in the application tray) on Android

Add shortcut to connect to VPN
Add shortcut to disconnect VPN

**Comment by eduardoaddad** [comment]
In the last update this was not deploying correctly

**Comment by artemiv4nov** [comment]
Sorry, this function is available on the 2.0 pre-alpha version.
