### ISSUE TITLE
Please improve the UI of split-VPN function.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardVPNForAndroid#9]
@ameshkov 
Your now split-VPN function is divided into 2 parts: regular/selective mode and apps setting, which is bad design.
In the regular/selective mode section, you design to swipe the page for selecting regular/selective mode.
But users may be unfamiliar with this kind of selecting method.
We may think we only swipe it and **not select** it.
We are used to click for choosing something, not swipe for choosing something.

I suggest to combine regular/selective mode and apps setting to the same section, which is more instinctive.
1. In this section, have a switch to enable/disable split tunneling.
2. When disabling split tunneling, AG VPN is working for everything. No exclusions.
3. When enabling split tunneling, AG VPN is only working for specific domains or apps.
4. Under split tunneling, we have exclusive/inclusive mode for specific domains or apps.
inclusive mode: Only the selected domains or apps will go through AG VPN.
exclusive mode: The selected domains or apps won't go through AG VPN.

Your developers can have the reference from Windscribe VPN app.
https://play.google.com/store/apps/details?id=com.windscribe.vpn&hl=zh_TW

**Comment by lancelot-moon** [comment]
@ameshkov 
@Revertron 

The new description of regular mode is strange.
`AdGuard VPN won't work on websites from the list below`


`AdGuard VPN works on all websites, except for those from the list below`

**Comment by ameshkov** [comment]
We're trying to make strings shorter.
