### ISSUE TITLE
Dropped on voice app Signal, Discord itd 

### ISSUE THREAD

**Issue by gzenio22** [AdguardTeam/AdGuardVPNForAndroid#91]
The problem I want to report concerns VPN for all available devices Android, Ios, Windows etc.

When I have a VPN turned on, every few seconds to 2 minutes I get disconnected from the interlocutor on various chat applications, e.g. Signal or Discord (I can't even enter the voice server on discord, i.e. I'm connected but I can't hear anyone) In my opinion, this is a critical problem :(

**Comment by admitrevskiy** [comment]
@gzenio22 Hi!
Are there any updates on this issue? Please let me know if issue has been fixed in one of the latest releases. 
Otherwise, please collect the logs as described above and send it to `devteam@adguard.com`.
