### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardVPNForAndroid#93]
> I would like to know whether there will be also an app for Android TV or Fire TV Stick in the future? I would also like to save locations as favorites, so I can access them quickly.

Requested by 511551, 529630, and many others

**Comment by Chinaski1** [comment]
The fact is that most TV`s do not have Google Play Market and AdGuard VPN is only available there.
Perhaps in the future, there will be other platforms to distribute the VPN application, then we will consider adding full support for TV as well.

About favourites locations: 
- There are no plans to add this function at this stage. We may come back to it later.

**Comment by sankeerthb** [comment]
Upvote for this. Most of the similar services exist on Android / Google TV Play store.

**Comment by infinitewaveparticle** [comment]
Just sideload AdGuard VPN from apkmirror.com

**Comment by Smithienious** [comment]
It's more about the UI than sideloading.

**Comment by olavinto** [comment]
> It's more about the UI than sideloading.
You can use a mouse and keyboard (wired/bluetooth) with most Android TV devices too. Or a mobile remote app of some kind. Not the ideal choice, obviously, but most apps work just fine like that. As a bonus it makes typing much easier.

**Comment by ishNoom** [comment]
> Just sideload AdGuard VPN from apkmirror.com

is this possible with Sony Bravia Android TV? I installed Aptoide but still can't get it to sideload apps.

**Comment by infinitewaveparticle** [comment]
I'm not familiar with Sony's interface or limitations. You would need to enable "Install Unknown Apps" in the system settings for an internet browser app and then use that browser to go to apkmirror.com. Then search for AdGuard VPN and install whatever version you want. I recommend the latest prior to 2.0.x because I can't get 2.0.x to work properly yet.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by TPS** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1148 would be very useful for this.

**Comment by artemiv4nov** [comment]
Well, the Android TV version has already been released, I'll close the task
