### ISSUE TITLE
Cannot start google drive downloads with VPN enabled

### ISSUE THREAD

**Issue by jenabaivab** [AdguardTeam/AdGuardVPNForAndroid#95]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes] I am running the latest version
- [yes] I checked the documentation and found no answer
- [yes] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  1.2 (35)
- **VPN mode:**
  - Local VPN
- **Device:**
  - Realme X2
- **Operating system and version:**
  -  Android 10
- **Root access:**
  - No

### Expected Behavior

Google drive downloads should start as soon as I press download button.
### Actual Behavior
The download doesn't start, keeps saying no internet access, even though internet is available.

Downloads from Google drive app are not starting. Tried changing servers, same problem everywhere.
### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by anastenko** [comment]
@jenabaivab Couldn't reproduce it on our end. Does it depend on the type of network you use (Wifi/Mobile)?

**Comment by jenabaivab** [comment]
@anastenko it doesn't actually. Tried with both mobile data and wifi, no difference.

**Comment by anastenko** [comment]
In this case we'll need to get the app logs.

Here's what we need you to do:

- Open AdGuard VPN settings;
- Advanced settings -> Logging level -> Extended;
- Reproduce the issue (and remember the exact time when it happened);
- Export logs and system info
 
Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by jenabaivab** [comment]
@anastenko the app logs are provided, along with video proof. The timings are 2:21 PM and 2:22 PM IST, but you can cross check the time in the logs with the screen recorded video as well

**Comment by anastenko** [comment]
@jenabaivab Thanks, received the logs. 
Now trying to figure out what causes the issue. Meanwhile, could you try to produce the same issue using any other VPN?
If it doesn't occur with another VPN then the issue is definitely on our side.

**Comment by jenabaivab** [comment]
@anastenko it seems, google drive is faulty with VPNs. I tried with express vpn, and still wasn't able to download files. 
Anything that can be found from logs regarding why this is happening?

**Comment by artemiv4nov** [comment]
Try to play with the following package names from VPN, adding/removing them from settings:
com.android.providers.downloads
com.android.providers.downloads.ui

So, you have to find the "Excluded apps" low-level setting, which will have these package names.
Please try to remove them and download something from Google Drive again.

**Comment by jenabaivab** [comment]
@artemiv4nov tried it just now, didn't help. Tried adding exclusions to google drive as well, nothing works.

**Comment by artemiv4nov** [comment]
If you want to help us to investigate a problem deeper, please collect the Android Bug report.

To collect this report, please read the following article: https://developer.android.com/studio/debug/bug-report

**Comment by anastenko** [comment]
@jenabaivab Have you already sent us the Android Bug report?

**Comment by jenabaivab** [comment]
@anastenko I actually tried to find the 'Take Bug Report' option on my 'Developer Options Tab', but there wasn't any such button.

**Comment by anastenko** [comment]
@jenabaivab I see, in this way maybe it looks like this:
Bug report -> Interactive/Full report -> "Report" button
It should be generated right after you click "Report". You can swipe down to see it in notification bar. 
Send it to devteam@adguard.com and mention this issue number in the subject.

**Comment by jenabaivab** [comment]
@anastenko still no option like it. Here is the list of all options in my Developer Options

**Comment by anastenko** [comment]
@jenabaivab Understood you. Android Bug report is just an additional thing, so there's no problem if you can't generate it.
 We'll try to figure out the issue and let you know once we have any information.

**Comment by artemiv4nov** [comment]
@jenabaivab Can you try to play with the "excluded apps" low-level setting again?
Try to remove 1000 or 1001 or both.

**Comment by admitrevskiy** [comment]
@jenabaivab Hi!
Could you restore default excluded apps list and add new package `com.coloros.providers.downloads.ui` into it?

It should contain the following (uncommented) entries:
```
1000
1001
com.android.providers.downloads
com.android.providers.downloads.ui
com.coloros.providers.downloads.ui
```

**Comment by jenabaivab** [comment]
@admitrevskiy well, damn. All this time we just had to find the right package to exclude huh. It works now.

**Comment by admitrevskiy** [comment]
Looks like realme uses it's own download manager instead of the default one. We should add it to default package exclusions list alongside with AdGuard.
