### ISSUE TITLE
Just Eat & Papa John's being blocked with Adguard VPN

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardVPNForAndroid#99]
![Screenshot_20210302-133725.png](https://user-images.githubusercontent.com/72349391/120889937-94dc6d80-c5f7-11eb-87ab-67344edf5f13.png)

The app loads fine but it blocks items in the burger menu and I cannot order anything.

**Comment by anastenko** [comment]
@Perfectlynk Hi. 
Couldn't reproduce it on my side. So "Just eat" starts its normal work after AdGuard VPN being disabled? Did you try to clear cache of "Just eat" app?
Please give more info on how to reproduce it.

**Comment by Perfectlynk** [comment]
> @Perfectlynk Hi. 
> Couldn't reproduce it on my side. So "Just eat" starts its normal work after AdGuard VPN being disabled? Did you try to clear cache of "Just eat" app?
> Please give more info on how to reproduce it.

Hello. No, even with the VPN I can access the app fine. I can look at items but I cannot order anything and the burger menu "your orders", "notification preference" etc, won't load and comes up in error. I cleared the cache but it doesn't help.

**Comment by anastenko** [comment]
@Perfectlynk To troubleshoot this issue, we'll need to get the app logs.

Here's what we need you to do:

* Open AdGuard VPN settings;
* Advanced settings -> Logging level -> Extended;
* Reproduce the issue (and remember the exact time when it happened);
* Export logs and system info. Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by Perfectlynk** [comment]
@anastenko 

I've sent the zip file.

**Comment by anastenko** [comment]
@Perfectlynk Thanks, received the logs. We'll have a look at it and let you know if we find something.

**Comment by artemiv4nov** [comment]
@Perfectlynk Hi!
I looked at your logs: all connections from the "Papa Johns" app established successfully. 
I think another app blocked connections (am I right, you use AdGuard together with AdGuard VPN?).
As a mitigating solution, you can disable the Ad blocking or traffic filtering for this app in AdGuard.
If you want to continue investigating a case, you can collect the debug logs from AdGuard.
And remember the exact time (hour/minute/second) of the issue reproducing, please.

**Comment by Perfectlynk** [comment]
Hello, I have attached the Adguard logs. I have reproduce the issue with
just eat and Papa John's. Everything starts at 21:24/5 on 19 June 21.
Adguard and Adguard VPN on together.

Thanks

**Comment by Perfectlynk** [comment]
Sorry i forgot to attach the logs last email. *facepalm*

**Comment by artemiv4nov** [comment]
Sent them to devteam@adguard.com, please.

**Comment by admitrevskiy** [comment]
@Perfectlynk Hi!
The last batch of logs contains only logs from AdGuard, so it's incredibly hard to say what went wrong.
Could you recollect the logs and send them for both applications?

BTW, I managed to reproduce the issue just without connecting to the VPN. At least outwardly, the behavior is very similar: it has the same error code.

**Comment by admitrevskiy** [comment]
In addition, as far as I can see, depending on the selected location, the behavior of the Just eat application changes. Could you try switching to another location, e.g. Germany?

**Comment by Perfectlynk** [comment]
@admitrevskiy Hello. I have sent new Adguard and Adguard VPN logs. I have also tried to access Papa John's and Just Eat from Germany Servers. 
Papa John's won't access the app but Just Eat seems to work perfectly fine. I can access notifications and orders. For you works in both servers but notifications and orders are still broken in UK servers.

**Comment by anastenko** [comment]
@Perfectlynk Hello, sorry for the late reply.
If the apps performance depends on the server, then we are unlikely to do anything.
You can try to exclude those applications in `apps management` .

**Comment by Perfectlynk** [comment]
Hello. Uber eats works through Adguard VPN just fine but why can't Just eat and Papa John's?

**Comment by Birbber** [comment]
@Perfectlynk Hi!
Sorry for the late response. Our devs are still working on this issue, and there wasn't any information on it.
- Did you try testing it with some other VPN app? Could you try if you didn't?
- Also please specify if the issue is reproducible with AdGuard Adblocker + AdGuard VPN only, or can it be seen even with AdGuard VPN alone?

**Comment by Perfectlynk** [comment]
> @Perfectlynk Hi!
> Sorry for the late response. Our devs are still working on this issue, and there wasn't any information on it.
> - Did you try testing it with some other VPN app? Could you try if you didn't?
> - Also please specify if the issue is reproducible with AdGuard Adblocker + AdGuard VPN only, or can it be seen even with AdGuard VPN alone?

Hello, not a problem. It happens with Adguard VPN not Adguard Ad-blocker. If I turn off the VPN it works fine. 

I don't have access to another VPN.

**Comment by Birbber** [comment]
@Perfectlynk Can you switch between different locations and tell as the result?
You mentioned that the issue was reproduced on UK servers.

**Comment by Perfectlynk** [comment]
> @Perfectlynk Can you switch between different locations and tell as the result?
> You mentioned that the issue was reproduced on UK servers.

Yes. The issue is the UK servers. Just checked, works on servers that are - France, Netherlands, Germany doesn't work in Japan or Taiwan.

**Comment by Birbber** [comment]
@Perfectlynk If it works for some locations than it's not an issue on the AdGuard's side. You should probably ask Just eat / Papa John's support why they have such location policy.
